# Trading Agent Development
Inspiration:
- https://www.backtrader.com/blog/posts/2015-08-16-backtesting-with-almost-no-programming/backtesting-with-almost-no-programming/ (Backtrader Platform würde einige Funktionen bereitstellen)
- https://github.com/tmorgan4/btgym_Kismuz?tab=readme-ov-file
-

In [1]:
from multiprocessing.managers import Value

import src.utils.file_management as filemgmt
import src.pipeline.preprocessing as preprocessing
import src.pipeline.predictors as predictors
from src.pipeline.predictors import LSTMPredictor, TransformerPredictor
from src.pipeline.rl_environments import RLTradingEnv
from src.pipeline.rl_agents import MultiProductAgent 
from src.pipeline.financial_products import KOCertificate, KOCertificateSet

from itertools import product
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3 import DQN
from typing import Union, Literal
import numpy as np
import pandas as pd
import random
import enum

from pathlib import Path

from tqdm import tqdm
from alpha_vantage.timeseries import TimeSeries

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from matplotlib.lines import Line2D

import matplotlib.pyplot as pl

## Initialisation

In [2]:
#matplotlib backend:
try:
    %matplotlib macosx
except BaseException:
    %matplotlib macosx
    # sometimes takes two tries...
    
# opens in separate window

#%matplotlib notebook
# opens in notebook

In [3]:
ROOT = Path().resolve().parent

DATA = ROOT / "data"
INTERPOLATED_PRICES = DATA / "interpolated_prices_dax"

SAVED_LSTM_MODELS = DATA / "saved_models" / "lstm"
SAVED_TF_MODELS = DATA / "saved_models" / "transformer"

TRAINING_LOGS = ROOT / "output" / "rl_training_logs"

PRIVATE_FILES = ROOT / "private"
AV_API_KEY_FILE = PRIVATE_FILES / "Alpha Vantage API Key.txt"
with open(AV_API_KEY_FILE) as file: AV_API_KEY = file.read()

In [4]:
# hourly data:
SAVED_B1_LSTM_PRED_556 = SAVED_LSTM_MODELS / "b_hourly_data" / "2025-07-28 13_16_18 LSTM Model RW42 FH14 Layers4 Size256 TrainL0.2269753264845349 ValL0.05964132840745151 TrainHR0.5311934947967529 ValHR0.5559566617012024.pt"
SAVED_B2_LSTM_PRED_557 = SAVED_LSTM_MODELS / "b_hourly_data" / "2025-07-28 15_54_59 LSTM Model RW70 FH14 Layers3 Size256 TrainL0.30958290363196284 ValL0.09781504119746387 TrainHR0.5377657413482666 ValHR0.5569620132446289.pt"

SAVED_B1_TF_PRED_542 = SAVED_TF_MODELS / "b_hourly_data" / "2025-07-29 05_00_35 Transformer Model RW42 FH14 Layers3 Size512 Heads16 TrainL0.6157988728955388 ValL0.3280078349635005 TrainHR0.49547919631004333 ValHR0.5415162444114685.pt"

# daily data:
SAVED_C1_LSTM_PRED_619 = SAVED_LSTM_MODELS / "c_daily_data" / "2025-07-29 10_52_54 LSTM Model RW15 FH3 Layers4 Size256 TrainL0.5109546836465597 ValL0.15437627281062305 TrainHR0.6462306976318359 ValHR0.6188747882843018.pt"
SAVED_C2_LSTM_PRED_705 = SAVED_LSTM_MODELS / "c_daily_data" / "2025-07-29 11_10_59 LSTM Model RW40 FH5 Layers3 Size256 TrainL0.5822748932987452 ValL0.1824055234901607 TrainHR0.7123852968215942 ValHR0.7051281929016113.pt"

SAVED_C1_TF_PRED_534 = SAVED_TF_MODELS / "c_daily_data" / "2025-07-29 12_24_40 Transformer Model RW15 FH3 Layers3 Size512 Heads16 TrainL2.661198813468218 ValL0.8520454280078411 TrainHR0.5399636626243591 ValHR0.5335752964019775.pt"
SAVED_C2_TF_PRED_542 = SAVED_TF_MODELS / "c_daily_data" / "2025-07-29 12_48_04 Transformer Model RW40 FH5 Layers3 Size256 Heads16 TrainL2.4900605091825128 ValL0.5748474728316069 TrainHR0.5307339429855347 ValHR0.5421245694160461.pt"

# weekly data:
SAVED_D1_LSTM_PRED_667 = SAVED_LSTM_MODELS / "d_weekly_data" / "2025-07-29 14_10_26 LSTM Model RW16 FH2 Layers4 Size256 TrainL0.39238258823752403 ValL0.11338997259736061 TrainHR0.5687645673751831 ValHR0.6666666865348816.pt"
SAVED_D2_LSTM_PRED_792 = SAVED_LSTM_MODELS / "d_weekly_data" / "2025-07-29 14_15_20 LSTM Model RW24 FH3 Layers3 Size256 TrainL0.2899367194622755 ValL0.09412111341953278 TrainHR0.741706132888794 ValHR0.7924528121948242.pt"
SAVED_D3_LSTM_PRED_911 = SAVED_LSTM_MODELS / "d_weekly_data" / "2025-07-29 14_32_49 LSTM Model RW48 FH6 Layers4 Size256 TrainL0.1885785385966301 ValL0.05248359590768814 TrainHR0.8924999833106995 ValHR0.9108911156654358.pt"

SAVED_D1_TF_PRED_574 = SAVED_TF_MODELS / "d_weekly_data" / "2025-08-04 12_26_55 Transformer Model RW16 FH2 Layers2 Size256 Heads16 TrainL1.084182608872652 ValL0.2614380903542042 TrainHR0.5477855205535889 ValHR0.5740740895271301.pt"
SAVED_D2_TF_PRED_613 = SAVED_TF_MODELS / "d_weekly_data" / "2025-07-17 17_41_32 Transformer Model RW24 FH3 Layers6 Size256 Heads16 TrainL0.3821653798222542 ValL0.07798176817595959 TrainHR0.5734597444534302 ValHR0.6132075190544128.pt"
SAVED_D3_TF_PRED_743 = SAVED_TF_MODELS / "d_weekly_data" / "2025-07-29 14_56_59 Transformer Model RW48 FH6 Layers3 Size256 Heads8 TrainL1.404388252645731 ValL0.5182094983756542 TrainHR0.7200000286102295 ValHR0.7425742745399475.pt"

In [5]:
ENV_PRICE_FILE = filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '15min')  #filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '15min')
B_PRICE_FILE = filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '60min')
C_PRICE_FILE = filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '1d')
D_PRICE_FILE = filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '7d')
MEAN_ETF_INDEX_RATIO = 543.3079783216567  # because files are etf prices

## Products

In [6]:
'''dax_long1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
                         isin='DE000TT2CH77',
                         date_base_price_tuple2=("2022-09-26 12:00:00", 10300)
                         # historic_date_future_price_tuple=("2022-09-26", 6.49),
                        )
dax_long1.plot()

dax_long1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
                         isin='DE000TT2CH77',
                         date_base_price_tuple2=("2022-09-26 12:00:00", 10300)
                         # historic_date_future_price_tuple=("2022-09-26", 6.49),
                        )
dax_long1.plot()

dax_long2 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
                         isin='DE000HS3U0K3',
                          direction='long',
                        )

dax_short1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
                         isin='DE000HT2PK31',
                         #historic_date_future_price_tuple=("2024-01-08", 1.31),
                        )
dax_short1.plot()

dax_short2 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
                         isin='DE000HT2LDF5',
                        )
dax_short2.plot()'''

'dax_long1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,\n                         isin=\'DE000TT2CH77\',\n                         date_base_price_tuple2=("2022-09-26 12:00:00", 10300)\n                         # historic_date_future_price_tuple=("2022-09-26", 6.49),\n                        )\ndax_long1.plot()\n\ndax_long1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,\n                         isin=\'DE000TT2CH77\',\n                         date_base_price_tuple2=("2022-09-26 12:00:00", 10300)\n                         # historic_date_future_price_tuple=("2022-09-26", 6.49),\n                        )\ndax_long1.plot()\n\ndax_long2 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,\n                         isin=\'DE000HS3U0K3\',\n                          direction=\'long\',\n                        )\n\ndax_short1 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,\n                         isin=\'DE000HT2PK31\',\n                         #historic_date_future_price_tuple=("2024-01-08", 1.31),\n                        )\ndax_short1.plot()\n\ndax_short2 = KOCertificate(preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,\n                         isin=\'DE000HT2LDF5\',\n                        )\ndax_short2.plot()'

### Portfolio Construction

In [7]:
# initialise for 2020/07, 2022/07, 2024/01
portfolio = KOCertificateSet(
    underlying_price_series=preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
    base_price_inference_timestamps=["2020-07-06 10:00:00", "2022-07-05 10:00:00", "2024-01-05 10:00:00"], # "2023-07-05 10:00:00", "2024-07-05 10:00:00", "2025-03-05 10:00:00"],
    n_products_per_direction=15,
    lowest_leverage=1.0, highest_leverage=10.0)

# add several other with more recent issue dates
portfolio.future_product_instances += portfolio.initialise_products_from_leverage(underlying_price_series=preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
    base_price_inference_timestamps=["2017-12-08 10:00:00", "2018-07-05 10:00:00"],
    n_products_per_direction=15, issue_date="2017-01-01 10:00:00",
    lowest_leverage=1.0, highest_leverage=10.0)

portfolio.future_product_instances += portfolio.initialise_products_from_leverage(underlying_price_series=preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
    base_price_inference_timestamps=["2021-07-06 10:00:00", "2023-07-05 10:00:00", "2024-07-05 10:00:00", "2025-03-05 10:00:00"],
    n_products_per_direction=15, issue_date="2020-06-01 10:00:00",
    lowest_leverage=1.0, highest_leverage=10.0)

portfolio.future_product_instances += portfolio.initialise_products_from_leverage(underlying_price_series=preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
    base_price_inference_timestamps=["2023-05-05 10:00:00", "2024-07-05 10:00:00", "2025-03-05 10:00:00"],
    n_products_per_direction=15, issue_date="2022-12-01 10:00:00",
    lowest_leverage=1.0, highest_leverage=10.0)

portfolio.future_product_instances += portfolio.initialise_products_from_leverage(underlying_price_series=preprocessing.read_price_csv(ENV_PRICE_FILE) * MEAN_ETF_INDEX_RATIO,
    base_price_inference_timestamps=["2025-03-05 12:00:00"],
    n_products_per_direction=15, issue_date="2024-03-03 10:00:00",
    lowest_leverage=1.0, highest_leverage=10.0)

30it [00:00, 47.75it/s]
30it [00:00, 50.88it/s]
30it [00:00, 44.46it/s]
30it [00:01, 29.44it/s]
30it [00:00, 30.67it/s]
30it [00:00, 41.73it/s]
30it [00:00, 43.64it/s]
30it [00:00, 38.90it/s]
30it [00:00, 37.70it/s]
30it [00:00, 57.30it/s]
30it [00:00, 38.83it/s]
30it [00:00, 58.42it/s]
30it [00:00, 73.16it/s]

In [8]:
#portfolio.plot_leverages()

In [9]:
#{product.isin: product.base_price_change_per_annum for product in portfolio.future_product_instances}

In [10]:
#long_avail_frame = portfolio.get_leverage_availability("long", hour_minute_to_check=(20, 0))
#short_avail_frame = portfolio.get_leverage_availability("short", hour_minute_to_check=(20, 0))

## Predictors

In [11]:
lstm_predictor_list = [LSTMPredictor(model_load_file_path=model_file,
                                     price_csv_path=price_file,
                                     preset_type=pred_type,
                                     name=name,
                                     ) for model_file, price_file, pred_type, name in
                       zip([SAVED_B1_LSTM_PRED_556, SAVED_B2_LSTM_PRED_557, SAVED_C1_LSTM_PRED_619, SAVED_C2_LSTM_PRED_705,
                            SAVED_D1_LSTM_PRED_667, SAVED_D2_LSTM_PRED_792, SAVED_D3_LSTM_PRED_911],
                           [B_PRICE_FILE] * 2 + [C_PRICE_FILE] * 2 + [D_PRICE_FILE] * 3,
                           ["b1", "b2", "c1", "c2", "d1", "d2", "d3"],
                           ["b1_LSTM_HR556", "b2_LSTM_HR557", "c1_LSTM_HR619", "c2_LSTM_HR705", "d1_LSTM_HR667", "d2_LSTM_HR792", "d3_LSTM_HR911"],
                           )]
b1_LSTM_HR556, b2_LSTM_HR557, c1_LSTM_HR619, c2_LSTM_HR705, d1_LSTM_HR667, d2_LSTM_HR792, d3_LSTM_HR911 = lstm_predictor_list

No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define LSTMPredictor.n_train_epochs to start training procedure.

In [12]:
tf_predictor_list = [TransformerPredictor(model_load_file_path=model_file,
                                          price_csv_path=price_file,
                                          preset_type=pred_type,
                                          name=name,
                                          ) for model_file, price_file, pred_type, name in
                     zip([SAVED_B1_TF_PRED_542, SAVED_D2_TF_PRED_613, SAVED_D3_TF_PRED_743],
                         [B_PRICE_FILE] + [D_PRICE_FILE] * 2,
                         ["b1", "d2", "d3"],
                         ["b1_TF_HR542", "d2_TF_HR613", "d3_TF_HR723"],
                         )]
b1_TF_HR542, d2_TF_HR613, d3_TF_HR723 = tf_predictor_list

No training epochs defined upon initialisation. Define n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define n_train_epochs to start training procedure.
No training epochs defined upon initialisation. Define n_train_epochs to start training procedure.

## Environment
https://github.com/tmorgan4/btgym_Kismuz/blob/master/btgym/strategy/base.py

In [24]:
def env_parametrisation_loop(env_price_file_path: Path,
                             env_price_sampling_rate_minutes: int,
                             env_product_set: KOCertificateSet,
                             agent_potential_threshold_steps: (float, float, float) = (.03, .1, .7),
                             sort_metric: Literal['Mean', 'Median', 'StdDev', 'Min', 'Max', 'SharpeRatio'] = 'Mean',
                             print_progress: bool = True,
                             **param_grid_and_constants):
    """
    Backtest multiple hyperparameter settings for RLTradingEnv class.

    Automatically infers parameter grid from provided keyword arguments.

    Provide lists of values for parameters to vary, and single values for constants.
    """
    # Identify grid parameters (iterables) and constant parameters
    grid_params = {k: v for k, v in param_grid_and_constants.items() if isinstance(v, list)}
    constant_params = {k: v for k, v in param_grid_and_constants.items() if k not in grid_params}

    # result frame with columns for all varying parameters and resulting metrics:
    columns = list(grid_params.keys()) + ['Mean', 'Median', 'StdDev', 'Min', 'Max', 'SharpeRatio']
    result_array = []  # initialise result array

    # all possible ordered pairs of grid parameters:
    n_configs = len(list(product(*grid_params.values())))
    for config_ind, config in enumerate(product(*grid_params.values())):
        if print_progress: print(f"\n--------- Backtest Config {config_ind + 1} / {n_configs} ---------")
        
        params = dict(zip(grid_params.keys(), config))
        env_kwargs = {
            **params,
            **constant_params,
            'verbose': False,
            'price_csv_path': env_price_file_path,
            'price_sampling_rate_minutes': env_price_sampling_rate_minutes,
            'product_set': env_product_set,
        }
        
        agent_kwargs = {}
        try:  # if agent potential threshold steps defined in env, add to agent_kwargs dict and remove from env_kwargs
            agent_kwargs['abs_potential_treshold_steps'] = env_kwargs['abs_potential_treshold_steps']
            del env_kwargs['abs_potential_treshold_steps']
        except KeyError:
            pass

        try:
            temp_env = RLTradingEnv(**env_kwargs)

            temp_agent = MultiProductAgent(**agent_kwargs,
                                           # infer other parameters from environment
                                           observation_types=temp_env.observation_types,
                                           observation_horizons_minute=temp_env.observation_horizons_minutes,
                                           n_leverage_categories=len(temp_env.leverage_categories),
                                           include_open_leverage_category=temp_env.include_open_leverage_category,
                                           potential_treshold_horizon_days=temp_env.potential_horizon_days, )

            # settings and losses:
            _, _, metric_tuple = temp_env.run_env_backtest(temp_agent, mute_environment=True, reset_environment=True,
                                                           track_portfolio_exposure_every=100000,
                                                           plot_results=False)
        except (ValueError, AttributeError) as e:
            print("Caught an exception:", e)
            metric_tuple = (np.nan, np.nan, np.nan, np.nan, np.nan, np.nan)
        
        # convert np values to regular values and concat to result row:
        metric_list = [metric.item() if isinstance(metric, np.float64) else metric for metric in metric_tuple]
        result_row = list(config) + [metric_list]
        result_array.append(result_row)  # append to result_array

    # convert to frame and sort eventually:
    results = pd.DataFrame(result_array, columns=columns)
    if sort_metric is not None:
        minimize = sort_metric in ['StdDev']
        results = results.sort_values(by=sort_metric, ascending=minimize)

    return results

In [25]:
print(lstm_predictor_list)
print(tf_predictor_list)

[b1_LSTM_HR556, b2_LSTM_HR557, c1_LSTM_HR619, c2_LSTM_HR705, d1_LSTM_HR667, d2_LSTM_HR792, d3_LSTM_HR911]
[b1_TF_HR542, d2_TF_HR613, d3_TF_HR723]

In [ ]:
result_frame = env_parametrisation_loop(env_price_file_path=ENV_PRICE_FILE, env_price_sampling_rate_minutes=15,
                                        env_product_set=portfolio,
                                        # varying params:
                                        predictor_instances=[[d3_LSTM_HR911],  # great predictors on their own
                                                             [d2_LSTM_HR792],
                                                             [c2_LSTM_HR705],
                                                             [d3_TF_HR723],
                                                             # combinations:
                                                             [c2_LSTM_HR705, d2_LSTM_HR792, d3_LSTM_HR911, d3_TF_HR723],
                                                             # all above 70
                                                             [d3_LSTM_HR911, d3_TF_HR723],  # both architectures D3
                                                             [d2_LSTM_HR792, d2_TF_HR613],  # both architectures D2
                                                             [b1_LSTM_HR556, b1_TF_HR542],  # both architectures b1
                                                             [b1_LSTM_HR556, b2_LSTM_HR557, b1_TF_HR542],
                                                             # all short term
                                                             [c1_LSTM_HR619, c2_LSTM_HR705],  # all mid term
                                                             [d1_LSTM_HR667, d2_LSTM_HR792, d3_LSTM_HR911, d2_TF_HR613,
                                                              d3_TF_HR723],  # all long term
                                                             lstm_predictor_list,  # all LSTMs
                                                             tf_predictor_list,  # all transformers
                                                             lstm_predictor_list + tf_predictor_list,  # all predictors
                                                             ],

                                        # constant params:
                                        trading_quantity_per_leverage_factor=1,
                                        sell_opposite_direction_if_no_cash=True,
                                        sell_all_opposite_products_if_no_cash=True,  #[False, True],
                                        include_open_leverage_category=False,
                                        precalculate_predictor_observations=True,
                                        leverage_categories=(1.0, 2.0, 3.0, 4.0, 5.0))
result_frame

--------- Backtest Config 1 / 14 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [00:35<00:00, 78.83it/s]
100%|█████████▉| 2433/2434 [16:19<00:00,  2.48it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 0.010584299757937522	Mean 0.005963150074380781	Std.Dev. 0.06011585463670066
			Max. 0.21386811956974364			Min. -0.2604918192383429
Alpha:		Median -8.109254198216537e-05	Mean -0.0052350098572689005	Std.Dev. 0.09274400451803397
			Max. 0.2782186868953311			Min. -0.49120846501708415
Sharpe Ratio: 0.06065759906019767 - Annual Sharpe Ratio: 0.363945594361186
Over-performed 49 / 113 epochs
--------- Backtest Config 2 / 14 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [00:13<00:00, 200.49it/s]
100%|█████████▉| 2601/2602 [18:52<00:00,  2.30it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median -0.0003799664817583572	Mean 0.004339282736627192	Std.Dev. 0.06342673701490942
			Max. 0.2898189289636877			Min. -0.26201053386220097
Alpha:		Median -9.107100891602576e-05	Mean -0.004331248731339733	Std.Dev. 0.10838819338776082
			Max. 0.4031661620889908			Min. -0.4927271796409419
Sharpe Ratio: 0.03188901345319213 - Annual Sharpe Ratio: 0.19133408071915278
Over-performed 55 / 121 epochs
--------- Backtest Config 3 / 14 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [00:29<00:00, 93.83it/s]
100%|█████████▉| 2729/2730 [15:46<00:00,  2.88it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 0.05563102781457109	Mean 0.10330611824085995	Std.Dev. 0.19214323761313554
			Max. 1.6141329601763081			Min. -0.10464805027967922
Alpha:		Median 0.037757602629212336	Mean 0.09499495611235675	Std.Dev. 0.2102583055085637
			Max. 1.808712612952027			Min. -0.1864084659360733
Sharpe Ratio: 0.5255946179980956 - Annual Sharpe Ratio: 3.1535677079885733
Over-performed 90 / 127 epochs
--------- Backtest Config 4 / 14 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [01:06<00:00, 41.52it/s]
100%|█████████▉| 2433/2434 [20:31<00:00,  1.98it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 0.015046927234077903	Mean 0.013863395503130881	Std.Dev. 0.06619137504822176
			Max. 0.17792658821447196			Min. -0.19445116741142213
Alpha:		Median -5.052811891642639e-06	Mean 0.0026652355714811985	Std.Dev. 0.06443383469413921
			Max. 0.28841399194902473			Min. -0.3367470842536536
Sharpe Ratio: 0.17444461348706217 - Annual Sharpe Ratio: 1.046667680922373
Over-performed 56 / 113 epochs
--------- Backtest Config 5 / 14 ---------
Pre-calculating potential estimates for all timestamps and predictors...

100%|██████████| 2770/2770 [02:16<00:00, 20.32it/s]
 81%|████████  | 1977/2434 [13:18<04:10,  1.83it/s]

In [16]:
# todo: round statistic print numbers and fix indentation

,predictor_instances,sell_all_opposite_products_if_no_cash,Mean,Median,StdDev,Min,Max
0,[------------------- LSTMPredictor Instance --...,False,NaN,NaN,NaN,NaN,NaN
1,[------------------- LSTMPredictor Instance --...,True,NaN,NaN,NaN,NaN,NaN
2,[------------------- LSTMPredictor Instance --...,False,NaN,NaN,NaN,NaN,NaN
3,[------------------- LSTMPredictor Instance --...,True,NaN,NaN,NaN,NaN,NaN
4,[------------------- LSTMPredictor Instance --...,False,NaN,NaN,NaN,NaN,NaN
5,[------------------- LSTMPredictor Instance --...,True,NaN,NaN,NaN,NaN,NaN
6,[------------------- TransformerPredictor Inst...,False,NaN,NaN,NaN,NaN,NaN
7,[------------------- TransformerPredictor Inst...,True,NaN,NaN,NaN,NaN,NaN
8,[------------------- TransformerPredictor Inst...,False,NaN,NaN,NaN,NaN,NaN
9,[------------------- TransformerPredictor Inst...,True,NaN,NaN,NaN,NaN,NaN
10,[[------------------- TransformerPredictor Ins...,False,NaN,NaN,NaN,NaN,NaN
11,[[------------------- TransformerPredictor Ins...,True,NaN,NaN,NaN,NaN,NaN

In [17]:
env = RLTradingEnv(ENV_PRICE_FILE,
                   price_sampling_rate_minutes=15,
                   # only predictors with val HR > 66%
                   predictor_instances=[predictor for predictor in lstm_predictor_list if predictor.sampling_rate_minutes == 5880 or (predictor.sampling_rate_minutes == 840 and predictor.rolling_window_size == 40)] + [predictor for predictor in tf_predictor_list if predictor.sampling_rate_minutes == 5880 and predictor.rolling_window_size == 48],
                   product_set=portfolio, trading_quantity_per_leverage_factor=1,
                   sell_opposite_direction_if_no_cash=True, sell_all_opposite_products_if_no_cash=True,
                   include_open_leverage_category=False,
                   precalculate_predictor_observations=False,  # FALSE MAKES SENSE ONLY FOR REDUCED N_STEPS IN BACKTEST
                   leverage_categories=(1.0, 2.0, 3.0, 4.0, 5.0))  #, 5.5, 6.0, 6.5, 7.0))

Starting at 2016-2-5 although data is provided since 2014-10-23 to have sufficient information for all predictors.

In [19]:
# env.current_potential_estimates

In [20]:
"""obs, _, _, _, info = env.step(10, track_portfolio_exposure=False)
print(obs)
print(info)
#self.open_positions"""

'obs, _, _, _, info = env.step(10, track_portfolio_exposure=False)\nprint(obs)\nprint(info)\n#self.open_positions'

## Agent

### Manual Agent

In [16]:
agent = MultiProductAgent(observation_types=env.observation_types,
                          observation_horizons_minute=env.observation_horizons_minutes,
                          n_leverage_categories=len(env.leverage_categories),
                          abs_potential_treshold_steps=(.03, .1, .7),  # (.04, .15, .7)
                          include_open_leverage_category=env.include_open_leverage_category,
                          potential_treshold_horizon_days=env.potential_horizon_days,
                          )

### RL Agent
With stable-baseline3 and pytorch.

Stable-Baselines3 is a reinforcement learning library built on top of PyTorch. It provides a set of pre-implemented RL algorithms and simplifies the process of training and evaluating RL models. It also includes a variety of useful tools for monitoring training progress and visualizing model behavior.

For training we will use Deep Q-Network (DQN). DQN is a reinforcement learning algorithm that uses a deep neural network to approximate the Q-value function. The Q-value function is a function that receives a status-action pair and outputs a value representing the expected cumulative reward for taking that action from that status, and continues playing following the optimal policy.

#### Agent Training

In [23]:
from stable_baselines3.common.env_checker import check_env
# check_env(env)

In [25]:
# MlpPolicy is policy used for training
# DummyVecEnc optimizes training through multiple independent variables
env.verbose = False  # mute environment
rl_agent = DQN('MlpPolicy', DummyVecEnv([lambda: env]), learning_rate=0.001, verbose=1)

Using cpu device

In [26]:
rl_agent.learn(total_timesteps=50000, log_interval=100, progress_bar=True)  # ~1s per iteration -> ~3600 iterations/h
rl_agent.save(filemgmt.file_title('DQN Trading Agent 100k iterations', dtype_suffix='.pt'))

Output()

In [ ]:
# only decision 'sell long 2.0-3.0' in backtest... what can cause stagnant decision-making?

In [25]:
# ponder:
# - training visualisation
# - reward shaping
# - initialisation
# - architecture

## Backtest

In [28]:
monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=rl_agent, track_portfolio_exposure_every=20,
                                                         reset_environment=True,
                                                         save_log_directory=TRAINING_LOGS, performance_time_unit='p.m.')

100%|█████████▉| 2433/2434 [24:55<00:00,  1.63it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median -0.0003775623638226969	Mean -0.017217729742190827	Std.Dev. 0.062366558744278086
			Max. 0.13920729313452138	Min. -0.31797556580127434
Alpha: 	Median -0.01720177719876938	Mean -0.02841588967384051	Std.Dev. 0.10478604041982394
			Max. 0.2895693743967548	Min. -0.3637487042342834
Over-performed 48 / 113 epochs

In [ ]:
# instead: fill alpha area green or red instead of extra line

In [18]:
env.current_step = 2600

In [19]:
monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=agent, track_portfolio_exposure_every=20,
                                                         reset_environment=False,
                                                         save_log_directory=TRAINING_LOGS, performance_time_unit='p.m.')

 99%|█████████▉| 169/170 [01:17<00:00,  2.19it/s]

--------- Policy p.m. Performance Statistics ---------
Policy: 	Median 0.03956270412265014	Mean 0.043417159316600035	Std.Dev. 0.13753701403073265
			Max. 0.28193118601466316			Min. -0.23567711252112744
Alpha:		Median 0.02283642557779626	Mean -0.006502598861421195	Std.Dev. 0.19270855653120028
			Max. 0.2337143290491988			Min. -0.46639375829986834
Sharpe Ratio: 0.298832230287837 - Annual Sharpe Ratio: 1.792993381727022
Over-performed 6 / 9 epochs

In [29]:
frame = pd.read_csv(filemgmt.most_recent_file(TRAINING_LOGS, file_title_keyword="Backtest Log"))
frame
#frame['Time'] = pd.to_datetime(frame['Time'])

,Time,Step,Reward,Action,Avg. Expected Potential / 90d,Cash,Total,Total Exposure,Time.1,Benchmark
0,2016-02-08 16:00:00,337,0.00,Sell long 2.0x - 3.0x,0.062306,1000000.00,1000000.00,NaN,2016-02-08 16:00:00,1.000000e+06
1,2016-02-09 16:00:00,338,0.00,Sell long 2.0x - 3.0x,0.260590,1000000.00,1000000.00,NaN,2016-02-09 16:00:00,9.992329e+05
2,2016-02-10 16:00:00,339,0.00,Sell long 2.0x - 3.0x,0.269888,1000000.00,1000000.00,NaN,2016-02-10 16:00:00,1.005155e+06
3,2016-02-11 16:00:00,340,0.00,Sell long 2.0x - 3.0x,0.279734,1000000.00,1000000.00,NaN,2016-02-11 16:00:00,9.933037e+05
4,2016-02-12 16:00:00,341,0.00,Sell long 2.0x - 3.0x,0.341152,1000000.00,1000000.00,0.0,2016-02-12 16:00:00,1.000672e+06
...,...,...,...,...,...,...,...,...,...,...
2428,2025-05-29 16:00:00,2765,46.04,Buy short 2.0x - 3.0x,-0.206763,11490.92,99634.90,NaN,2025-05-29 16:00:00,2.537947e+06
2429,2025-05-30 16:00:00,2766,-19.54,Sell long 2.0x - 3.0x,-0.241880,11490.92,99615.36,NaN,2025-05-30 16:00:00,2.539676e+06
2430,2025-06-02 16:00:00,2767,203.22,Sell long 2.0x - 3.0x,-0.147841,11490.92,99818.58,NaN,2025-06-02 16:00:00,2.529589e+06
2431,2025-06-03 16:00:00,2768,-220.56,Sell long 2.0x - 3.0x,-0.087222,11490.92,99598.02,NaN,2025-06-03 16:00:00,2.541982e+06
2432,2025-06-04 16:00:00,2769,-486.78,Sell long 2.0x - 3.0x,-0.177217,11490.92,99111.24,NaN,2025-06-04 16:00:00,2.568497e+06

In [25]:
frame

,Time,Step,Reward,Action,Avg. Expected Potential / 90d,Cash,Total,Total Exposure,Benchmark,Time.1
0,2024-10-14 16:00:00,2602,3922.54,Sell long 4.0x - 5.0x,-0.015391,10526.26,627978.77,NaN,NaN,2024-10-14 16:00:00
1,2024-10-15 16:00:00,2603,2339.60,Hold,-0.034034,10526.26,630318.37,NaN,NaN,2024-10-15 16:00:00
2,2024-10-16 16:00:00,2604,-4414.78,Sell long 4.0x - 5.0x,0.009697,10526.26,625903.59,NaN,NaN,2024-10-16 16:00:00
3,2024-10-17 16:00:00,2605,706.59,Hold,0.114231,10526.26,626610.18,NaN,NaN,2024-10-17 16:00:00
4,2024-10-18 16:00:00,2606,596.48,Buy long 1.0x - 2.0x,0.096086,10526.26,627206.66,NaN,NaN,2024-10-18 16:00:00
...,...,...,...,...,...,...,...,...,...,...
163,2025-05-29 16:00:00,2765,304.25,Buy short 1.0x - 2.0x,-0.206763,677507.84,1087850.75,NaN,NaN,2025-05-29 16:00:00
164,2025-05-30 16:00:00,2766,-462.98,Buy short 1.0x - 2.0x,-0.241880,472260.31,1087387.77,NaN,NaN,2025-05-30 16:00:00
165,2025-06-02 16:00:00,2767,2748.41,Buy short 1.0x - 2.0x,-0.147841,266026.98,1090136.18,NaN,NaN,2025-06-02 16:00:00
166,2025-06-03 16:00:00,2768,-4741.25,Buy short 1.0x - 2.0x,-0.087222,60928.88,1085394.93,NaN,NaN,2025-06-03 16:00:00
167,2025-06-04 16:00:00,2769,-12325.97,Sell long 1.0x - 2.0x,-0.177217,60928.88,1073068.97,NaN,NaN,2025-06-04 16:00:00

In [28]:
type(pd.to_datetime(frame.set_index('Time').index))

pandas.core.indexes.datetimes.DatetimeIndex

In [22]:
isinstance(frame.set_index('Time').index, pd.DatetimeIndex)

True

In [19]:
env.plot_backtest_results(frame.set_index('Time'), plot_annual_returns=False)

Over-performed 53.09734513274337% of months

In [104]:
import matplotlib.pyplot as plt

plot_annual_returns = False
plot_size = (12, 5)

frame['Time'] = pd.to_datetime(frame.Time)
annual_return_frame = frame.loc[:, ['Total', 'Benchmark', 'Time']].groupby(frame.Time.dt.year if plot_annual_returns else [frame.Time.dt.year, frame.Time.dt.month]).agg(['first', 'last'])
annual_return_frame['Benchmark return'] = ((annual_return_frame['Benchmark', 'last'] - annual_return_frame['Benchmark', 'first']) / annual_return_frame['Benchmark', 'first']) * (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first']).max() / (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first'])

annual_return_frame['Policy return'] = (annual_return_frame['Total', 'last'] - annual_return_frame['Total', 'first']) / annual_return_frame['Total', 'first'] * (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first']).max() / (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first'])  # calculate relative development and normalise by time-duration
annual_return_frame['Over performance'] = annual_return_frame['Policy return'] > annual_return_frame['Benchmark return']

# result plot:
fig, ax = plt.subplots(figsize=plot_size)
ax2 = ax.twinx()
ax.plot(annual_return_frame.set_index([('Time', 'first')]).loc[:, ['Benchmark return', 'Policy return']] * 100, marker='o', label=['Benchmark', 'Policy'])
ax.set_xlabel('Datetime'); ax.set_ylabel(f"Return per {'annum' if plot_annual_returns else 'month'} [%]")
annual_return_frame['Over performance'] = annual_return_frame['Policy return'] > annual_return_frame['Benchmark return']

ax2.plot(annual_return_frame.set_index([('Time', 'first')]).loc[:, 'Over performance'], marker='s', linestyle='', color='Black')
ax2.set_ylabel('Performance Policy vs Benchmark')
ax2.set_yticks([0, 1]); ax2.set_yticklabels(['Under', 'Over'])
ax.legend(bbox_to_anchor=(0.5, -.3), loc='lower center')
print(f"Over-performed {annual_return_frame['Over performance'].value_counts()[True].item()/len(annual_return_frame)*100}% of {'years' if plot_annual_returns else 'months'}")
ax.grid()
fig.tight_layout()

Over-performed 53.09734513274337% of months

In [98]:
annual_return_frame['Over performance'].value_counts()[True].item()

6

In [50]:
annual_return_frame

            Total                  Benchmark                \
            first         last         first          last
Time
2016   1000000.00   1125538.30  1.000000e+06  1.184353e+06
2017   1129008.79   1348508.57  1.180851e+06  1.504055e+06
2018   1351917.95   1720917.53  1.507863e+06  1.182703e+06
2019   1740774.20   1468683.64  1.164954e+06  1.410989e+06
2020   1491072.99   7842089.90  1.432583e+06  1.601698e+06
2021   7859483.70   9479701.75  1.604761e+06  1.717990e+06
2022   9468268.84  11291636.06  1.730214e+06  1.410605e+06
2023  11217780.60  10291309.92  1.424105e+06  1.745433e+06
2024  10287803.99  12133463.31  1.734652e+06  1.926743e+06
2025  12153677.13  19272621.34  1.919826e+06  2.568497e+06

                    Time                     Benchmark p.a. Policy p.a.
                   first                last
Time
2016 2016-02-08 16:00:00 2016-12-30 16:00:00       0.184353    0.125538
2017 2017-01-02 16:00:00 2017-12-29 16:00:00       0.273704    0.194418
2018 2018-01-01 16:00:00 2018-12-31 16:00:00      -0.215642    0.272945
2019 2019-01-01 16:00:00 2019-12-31 16:00:00       0.211197   -0.156304
2020 2020-01-01 16:00:00 2020-12-31 16:00:00       0.118049    4.259360
2021 2021-01-01 16:00:00 2021-12-31 16:00:00       0.070558    0.206148
2022 2022-01-03 16:00:00 2022-12-30 16:00:00      -0.184722    0.192577
2023 2023-01-02 16:00:00 2023-12-29 16:00:00       0.225635   -0.082589
2024 2024-01-01 16:00:00 2024-12-31 16:00:00       0.110737    0.179403
2025 2025-01-01 16:00:00 2025-06-04 16:00:00       0.337880    0.585744

In [60]:
import matplotlib.pyplot as plt
annual_return_frame['Benchmark p.a.'] = ((annual_return_frame['Benchmark', 'last'] - annual_return_frame['Benchmark', 'first']) / annual_return_frame['Benchmark', 'first']) * (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first']).max() / (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first'])
annual_return_frame['Policy p.a.'] = (annual_return_frame['Total', 'last'] - annual_return_frame['Total', 'first']) / annual_return_frame['Total', 'first'] * (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first']).max() / (annual_return_frame['Time', 'last'] - annual_return_frame['Time', 'first'])  # calculate relative development and normalise by time-duration
fig, ax = plt.subplots()
ax.plot(annual_return_frame.set_index([('Time', 'first')]).loc[:, ['Policy p.a.', 'Benchmark p.a.']], marker='o')

[<matplotlib.lines.Line2D at 0x38586ec10>,
 <matplotlib.lines.Line2D at 0x38586ed50>]

In [58]:
annual_return_frame.set_index('Time')

KeyError: "None of ['first'] are in the columns"

## Run

NameError: name 'env' is not defined

In [ ]:
# add recent price data:
# env.price_csv_path = filemgmt.most_recent_file(INTERPOLATED_PRICES, '.csv', '15min')

In [20]:
# set current step to latest step:
env.current_step = env.total_steps - 1
env.current_step_timestamp

Timestamp('2025-07-17 16:00:00')

In [22]:
env.average_predicted_potential

0.10184113630236336

In [36]:
env.action_enum_dict[agent.predict(env.current_observation)[0]]

'Sell short 3.0x - 4.0x'