# Trading Agent Development
Inspiration:
- https://www.backtrader.com/blog/posts/2015-08-16-backtesting-with-almost-no-programming/backtesting-with-almost-no-programming/ (Backtrader Platform würde einige Funktionen bereitstellen)
- https://github.com/tmorgan4/btgym_Kismuz?tab=readme-ov-file

In [1]:
import src.utils.file_management as filemgmt
import src.pipeline.preprocessing as preprocessing
from src.pipeline.preprocessing import StockPriceDataManager
import src.pipeline.predictors as predictors
from src.pipeline.predictors import LSTMPredictor, TransformerPredictor, NNPredictor, PredictorManager
from src.pipeline.rl_environments import RLTradingEnv, env_parametrisation_loop
from src.pipeline.rl_agents import MultiProductAgent 
from src.pipeline.financial_products import KOCertificate, KOCertificateSet
import src.pipeline.web_interaction as webinteraction 

from itertools import product
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3 import DQN
from typing import Union, Literal
import numpy as np
import pandas as pd
import random
import enum

from pathlib import Path
import re

from tqdm import tqdm
from alpha_vantage.timeseries import TimeSeries

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from matplotlib.lines import Line2D

import matplotlib.pyplot as pl

## Initialisation

In [2]:
#matplotlib backend:
try:
    %matplotlib macosx
except BaseException:
    %matplotlib macosx
    # sometimes takes two tries...
# opens in separate window

#%matplotlib notebook
# opens in notebook

In [3]:
ROOT = Path().resolve().parent

DATA = ROOT / "data"
DOWNLOADED_PRICES = DATA / "minutely_price_downloads"
INTERPOLATED_PRICES = DATA / "interpolated_prices_dax"
SCRAPED_RAW_DOWNLOADS = DATA / "scraped_raw_downloads"

SAVED_MODELS = DATA / "saved_models"
SAVED_LSTM_MODELS = SAVED_MODELS / "lstm"
SAVED_TF_MODELS = SAVED_MODELS / "transformer"

SAVED_PORTFOLIOS = DATA / "portfolios"

SAVED_BACKTESTS = DATA / "backtests"

TRAINING_LOGS = ROOT / "output" / "rl_training_logs"

PRIVATE_FILES = ROOT / "private"
AV_API_KEY_FILE = PRIVATE_FILES / "Alpha Vantage API Key.txt"
with open(AV_API_KEY_FILE) as file: AV_API_KEY = file.read()

scenario : Literal['deployment', 'backtest'] = 'deployment'

## DataManager

In [4]:
data_manager = StockPriceDataManager(ticker_symbol='DAX',
                                    download_dir=DOWNLOADED_PRICES,
                                    interpolated_files_dir=INTERPOLATED_PRICES,
                                    alpha_vantage_api_key=AV_API_KEY,
                                    env_sampling_rate_minutes=15,
                                    is_etf_price_data=True,
                                    non_etf_time_price_tuples=[('2025-06-04 18:00:00', 24276.48),
                                                               ('2025-06-02 17:00:00', 23942.52),
                                                               ('2025-06-03 12:00:00', 23962.40),
                                                               ('2025-05-30 17:00:00', 23997.71)],
                                    include_scraped_downloads=(scenario == "deployment"),
                                     scrape_raw_download_dir=SCRAPED_RAW_DOWNLOADS,
                                    )

## PredictorManager

In [5]:
pred_manager = PredictorManager(data_manager=data_manager, initialisation_dir=SAVED_MODELS, recursive=True)

In [6]:
pred_manager.describe_preset_types()

Preset Details:

Preset 'a1':
  - Sampling Rate: 15 minute(s)
  - Rolling Window Size: 300 minute(s)
  - Forecast Horizon: 180 minute(s)
  - Prediction Time: 13.00
--------------------------------------------------
Preset 'b1':
  - Sampling Rate: 1 hour(s)
  - Rolling Window Size: 42 hour(s)
  - Forecast Horizon: 14 hour(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'b2':
  - Sampling Rate: 1 hour(s)
  - Rolling Window Size: 70 hour(s)
  - Forecast Horizon: 14 hour(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'c1':
  - Sampling Rate: 1 day(s)
  - Rolling Window Size: 15 day(s)
  - Forecast Horizon: 3 day(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'c2':
  - Sampling Rate: 1 day(s)
  - Rolling Window Size: 40 day(s)
  - Forecast Horizon: 5 day(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'd1':
  - Sampling Rate: 1 week(s)
  - Rolling Window Size: 16 week(s)
  - Forecast Horizon: 2 week(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'd2':
  - Sampling Rate: 1 week(s)
  - Rolling Window Size: 24 week(s)
  - Forecast Horizon: 3 week(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'd3':
  - Sampling Rate: 1 week(s)
  - Rolling Window Size: 48 week(s)
  - Forecast Horizon: 6 week(s)
  - Prediction Time: 16.00
--------------------------------------------------

## Portfolio

In [7]:
if scenario == "deployment":
    portfolio = KOCertificateSet.load_from_csv(
        file_path=filemgmt.most_recent_file(SAVED_PORTFOLIOS, ".csv", ["Scraped"]),
        underlying_price_series=data_manager.non_etf_env_interp_prices, )

    # update product details:
    for product in portfolio.ko_certificates:
        #product.update_product_details_from_scrape()
        pass
    #portfolio.save_to_csv(SAVED_PORTFOLIOS / filemgmt.file_title("Saved Certificate Set", ".csv"))

elif scenario == "backtest":
    portfolio = KOCertificateSet.load_from_csv(
        file_path=filemgmt.most_recent_file(SAVED_PORTFOLIOS, ".csv", ["Artificial"]),
        underlying_price_series=data_manager.non_etf_env_interp_prices, )

In [8]:
#portfolio.plot_leverages()

{product.isin: product.base_price_change_per_annum for product in portfolio.ko_certificates}

{'DE000TT2CH77': -0.08602477704837286,
 'DE000HS3U0K3': -0.10295866696697387,
 'DE000TT0ZP72': -0.10308423721727955,
 'DE000TT1WHV8': -0.09144340543340257,
 'DE000HG75555': -0.08941304825198004,
 'DE000HS2W424': -0.11563384480112149,
 'DE000HS3GYD5': -0.10589088257858714,
 'DE000HS8DSJ0': -0.14628467768495257,
 'DE000FA0RD26': 0.10751642924090277,
 'DE000FA0Q232': 0.11186793580071952,
 'DE000SX0LHS4': -0.10715283192277647,
 'DE000HT52AV7': -0.45835708654622065}

## Backtest Schedule
https://github.com/tmorgan4/btgym_Kismuz/blob/master/btgym/strategy/base.py

In [9]:
if scenario == "backtest":
    result_frame = env_parametrisation_loop(
        env_price_series=data_manager.env_interp_prices,
        env_price_sampling_rate_minutes=data_manager.env_sampling_rate_minutes,
        env_product_set=portfolio,
        backtest_database_dir=SAVED_BACKTESTS,
        # varying params:
        predictor_instances=[
            #pred_manager.get_predictors_by_type_sorted(architecture='LSTM', preset_type='c2', return_instances=True, k_best=1),
            #pred_manager.get_predictors_by_type_sorted(architecture='LSTM', return_instances=True, k_best=2),
            pred_manager.get_predictors_by_type_sorted(architecture='LSTM',
                                                       return_instances=True, k_best=3),
            #pred_manager.get_predictors_by_type_sorted(architecture='LSTM',return_instances=True, k_best=4),
        ],
    
        # constant params:
        # 90 day expected return, sell -> buy -> highest leverage
        abs_potential_threshold_steps=[(.0025, .04, .1),
                                       ],
        # balanced, offensive, defensive
        trading_quantity_per_leverage_factor=[1, 1.25, 1.5, 1.75, 2,
                                              2.25, 2.5, 2.75, 3],
        sell_opposite_direction_if_no_cash=True,
        sell_all_opposite_products_if_no_cash=True,  #[False, True],
        include_open_leverage_category=False,
        precalculate_predictor_observations=True,
        leverage_categories=(1.0, 2.0, 3.0, 4.0, 5.0))
    result_frame

In [10]:
previous_frame = pd.read_csv(filemgmt.most_recent_file(SAVED_BACKTESTS))
previous_frame.sort_values(by='Mean', ascending=False)

,predictor_instances,abs_potential_threshold_steps,Mean,Median,StdDev,Min,Max,SharpeRatio,trading_quantity_per_leverage_factor,sell_opposite_direction_if_no_cash,sell_all_opposite_products_if_no_cash,include_open_leverage_category,precalculate_predictor_observations,leverage_categories,date
53,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.0025, 0.04, 0.1)",0.117417,0.074664,0.257760,-0.362711,1.962385,0.519197,2.50,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-25
54,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.0025, 0.04, 0.1)",0.116449,0.061945,0.259297,-0.362503,1.936245,0.517403,2.25,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-25
55,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.0025, 0.04, 0.1)",0.116275,0.064159,0.254523,-0.362294,1.923900,0.526368,2.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-25
41,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.0025, 0.04, 0.1)",0.116275,0.064159,0.254523,-0.362294,1.923900,0.526368,2.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-25
42,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.0025, 0.04, 0.1)",0.116031,0.070729,0.259417,-0.362310,2.011028,0.508570,3.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925]","(0.025, 0.075, 0.6)",0.006644,0.003478,0.100070,-0.291681,0.340071,0.225091,1.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
16,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925]","(0.035, 0.125, 0.7)",0.004820,0.001483,0.101482,-0.304426,0.339057,0.188869,1.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
17,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.035, 0.125, 0.7)",0.004645,-0.000053,0.101228,-0.224698,0.401642,0.179952,1.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
18,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.025, 0.075, 0.6)",0.004577,0.000697,0.099339,-0.230125,0.349942,0.190271,1.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
19,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.035, 0.125, 0.7)",0.003840,-0.000115,0.102606,-0.226911,0.387994,0.167632,1.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24

## Environment

In [11]:
env = RLTradingEnv(price_series=data_manager.env_interp_prices,
                   price_sampling_rate_minutes=data_manager.env_sampling_rate_minutes,
                   predictor_instances=pred_manager.get_predictors_by_type_sorted(architecture='LSTM',
                                                                                  return_instances=True, k_best=3),
                   product_set=portfolio,
                   trading_quantity_per_leverage_factor=2.5,
                   sell_opposite_direction_if_no_cash=True, sell_all_opposite_products_if_no_cash=True,
                   include_open_leverage_category=False,
                   precalculate_predictor_observations=(scenario == 'backtest'),  # FALSE MAKES SENSE ONLY FOR REDUCED N_STEPS IN BACKTEST
                   leverage_categories=(1.0, 2.0, 3.0, 4.0, 5.0))  #, 5.5, 6.0, 6.5, 7.0))

Starting at 2015-9-24 although data is provided since 2014-10-23 to have sufficient information for all predictors.

In [12]:
#obs, _, _, _, info = env.step(3, track_portfolio_exposure=False)
#print(obs)
#print(info)
#self.open_positions"""

## Agent

### Manual Agent

In [13]:
agent = MultiProductAgent(observation_types=env.observation_types,
                          observation_horizons_minute=env.observation_horizons_minutes,
                          n_leverage_categories=len(env.leverage_categories),
                          abs_potential_threshold_steps=(.0025, .04, .1),  # (.04, .15, .7)
                          include_open_leverage_category=env.include_open_leverage_category,
                          potential_treshold_horizon_days=env.potential_horizon_days,
                          )

### RL Agent
With stable-baseline3 and pytorch.

Stable-Baselines3 is a reinforcement learning library built on top of PyTorch. It provides a set of pre-implemented RL algorithms and simplifies the process of training and evaluating RL models. It also includes a variety of useful tools for monitoring training progress and visualizing model behavior.

For training we will use Deep Q-Network (DQN). DQN is a reinforcement learning algorithm that uses a deep neural network to approximate the Q-value function. The Q-value function is a function that receives a status-action pair and outputs a value representing the expected cumulative reward for taking that action from that status, and continues playing following the optimal policy.

#### Agent Training

In [14]:
from stable_baselines3.common.env_checker import check_env
# check_env(env)

In [15]:
# MlpPolicy is policy used for training
# DummyVecEnc optimizes training through multiple independent variables
#env.verbose = False  # mute environment
#rl_agent = DQN('MlpPolicy', DummyVecEnv([lambda: env]), learning_rate=0.001, verbose=1)

In [16]:
#rl_agent.learn(total_timesteps=50000, log_interval=100, progress_bar=True)  # ~1s per iteration -> ~3600 iterations/h
#rl_agent.save(filemgmt.file_title('DQN Trading Agent 100k iterations', dtype_suffix='.pt'))

In [17]:
# only decision 'sell long 2.0-3.0' in backtest... what can cause stagnant decision-making?

In [18]:
# ponder:
# - training visualisation
# - reward shaping
# - initialisation
# - architecture

## Single Backtest

In [19]:
"""monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=rl_agent, track_portfolio_exposure_every=20,
                                                         reset_environment=True,
                                                         save_log_directory=TRAINING_LOGS, performance_time_unit='p.m.')"""

"monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=rl_agent, track_portfolio_exposure_every=20,\n                                                         reset_environment=True,\n                                                         save_log_directory=TRAINING_LOGS, performance_time_unit='p.m.')"

In [20]:
if scenario == 'backtest':
    monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=agent, track_portfolio_exposure_every=20,
                                                                         reset_environment=True,
                                                                         save_log_directory=TRAINING_LOGS,
                                                                         performance_time_unit='p.m.')

## Deployment

### Scrape Real-Time Data

In [ ]:
if scenario == "deployment":
    # update without scraping:
    data_manager.include_scraped_downloads = False
    data_manager.update()
    
    # update interpolated data with scraping:
    data_manager.include_scraped_downloads = True
    data_manager.update_interpolated_data()

### Inference

In [41]:
# here one more step can be executed:
env.current_step = env.total_steps - 2
env.current_step_timestamp

Timestamp('2025-08-22 16:00:00')

In [42]:
from typing import Literal
from datetime import datetime

class TradeImplementor:
    def __init__(self):
        self.action_log = {}

    def __call__(self, isin: str, amount: int, action: Literal['buy', 'sell']):
        today = datetime.today().strftime('%Y-%m-%d %H_%M_%S')
        self.action_log[today] = {"isin": isin, "amount": amount, "action": action, "completed": False}
    
    # todo: implement action execution and set "completed" to True

In [43]:
env.open_positions

Empty DataFrame
Columns: [Shares, Leverage, Price, Direction, % Portfolio]
Index: []

In [44]:
action, _ = agent.predict(env.current_observation)
trade_implementor = TradeImplementor()
new_obs, _, done, truncated, info = env.step(action, track_portfolio_exposure=False, start_new_episode_if_finished=False,
                                             trade_implementation_callback=trade_implementor)

[STEP 2827] Bought 81778.0 shares of DE000HS8DSJ0 (long with leverage in (4.0, 5.0)) at 6.107942097884995.
    Cash: 499505.7178321822, Holding: 498996.29258825094

### Execution

In [45]:
trade_implementor.action_log

{'2025-08-26 22_55_40': {'isin': 'DE000HS8DSJ0',
  'amount': np.float64(81778.0),
  'action': 'buy',
  'completed': False}}

In [36]:
info

{'Step': 2827,
 'Time': '2025-08-25 16:00:00',
 'Reward': -28087.59,
 'Action': 'Sell long 1.0x - 2.0x',
 'Avg. Expected Potential / 90d': 0.12966255006048563,
 'Cash': 999001.01,
 'Total': 999001.01}

In [ ]:
env.step(1, start_new_episode_if_finished=False)

In [46]:
portfolio.by_isin["DE000HS8DSJ0"].plot()

In [ ]:
env.total_steps

In [ ]:
# daily workflow:
#   data_manager.update()
#   portfolio.update_all_price_series(data_manager.non_etf_env_interp_prices)
#   env.price_series = data_manager.env_interp_prices
#

In [ ]:
# set current step to latest step:
env.current_step = env.total_steps - 1
env.current_step_timestamp

In [ ]:
env.average_predicted_potential

In [ ]:
env.action_enum_dict[agent.predict(env.current_observation)[0]]