# Trading Agent Development
Inspiration:
- https://www.backtrader.com/blog/posts/2015-08-16-backtesting-with-almost-no-programming/backtesting-with-almost-no-programming/ (Backtrader Platform würde einige Funktionen bereitstellen)
- https://github.com/tmorgan4/btgym_Kismuz?tab=readme-ov-file

In [1]:
import src.utils.file_management as filemgmt
import src.pipeline.preprocessing as preprocessing
from src.pipeline.preprocessing import StockPriceDataManager
import src.pipeline.predictors as predictors
from src.pipeline.predictors import LSTMPredictor, TransformerPredictor, NNPredictor, PredictorManager
from src.pipeline.rl_environments import RLTradingEnv, env_parametrisation_loop
from src.pipeline.rl_agents import MultiProductAgent 
from src.pipeline.financial_products import KOCertificate, KOCertificateSet
import src.pipeline.web_interaction as webinteraction
from src.pipeline.chatbot import WhatsAppChatbot

from itertools import product
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3 import DQN
from typing import Union, Literal
import numpy as np
import pandas as pd
import random
import enum

from pathlib import Path
import re

from tqdm import tqdm
from alpha_vantage.timeseries import TimeSeries

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from matplotlib.lines import Line2D

import matplotlib.pyplot as plt

## Initialisation

In [2]:
#matplotlib backend:
try:
    %matplotlib macosx
except BaseException:
    %matplotlib macosx
    # sometimes takes two tries...
# opens in separate window

#%matplotlib notebook
# opens in notebook

In [3]:
ROOT = Path().resolve().parent

DATA = ROOT / "data"
DOWNLOADED_PRICES = DATA / "minutely_price_downloads"
INTERPOLATED_PRICES = DATA / "interpolated_prices_dax"
SCRAPED_RAW_DOWNLOADS = DATA / "scraped_raw_downloads_archive"

SAVED_MODELS = DATA / "saved_models"
SAVED_LSTM_MODELS = SAVED_MODELS / "lstm"
SAVED_TF_MODELS = SAVED_MODELS / "transformer"
WORKING_DIR_PREDICTORS = SAVED_MODELS / "working_dir_pred_manager"

SAVED_PORTFOLIOS = DATA / "portfolios"

SAVED_BACKTESTS = DATA / "backtests"

TRAINING_LOGS = ROOT / "output" / "rl_training_logs"

PRIVATE_FILES = ROOT / "private"
AV_API_KEY_FILE = PRIVATE_FILES / "Alpha Vantage API Key.txt"
with open(AV_API_KEY_FILE) as file: AV_API_KEY = file.read()

WIKIFOLIO_KEY_FILE = PRIVATE_FILES / "Wikifolio key.txt"
with open(WIKIFOLIO_KEY_FILE) as file: WIKIFOLIO_USER_KEY = file.read().split('\n')

CHATBOT_ENV_FILE = PRIVATE_FILES / "chatbot.env"

scenario : Literal['deployment', 'backtest'] = 'deployment'

## DataManager

In [4]:
data_manager = StockPriceDataManager(ticker_symbol='DAX',
                                    download_dir=DOWNLOADED_PRICES,
                                    interpolated_files_dir=INTERPOLATED_PRICES,
                                    alpha_vantage_api_key=AV_API_KEY,
                                    env_sampling_rate_minutes=15,
                                    is_etf_price_data=True,
                                    non_etf_time_price_tuples=[('2025-06-04 18:00:00', 24276.48),
                                                               ('2025-06-02 17:00:00', 23942.52),
                                                               ('2025-06-03 12:00:00', 23962.40),
                                                               ('2025-05-30 17:00:00', 23997.71)],
                                    include_scraped_downloads=(scenario == "deployment"),
                                     scrape_raw_download_dir=SCRAPED_RAW_DOWNLOADS,
                                    )

## PredictorManager

In [5]:
pred_manager = PredictorManager(data_manager=data_manager, initialisation_dir=SAVED_MODELS, recursive=True,
                                not_older_than_n_days=10,  # only recently fine-tuned models
                                )

In [6]:
pred_manager.describe_preset_types()

Preset Details:

Preset 'a1':
  - Sampling Rate: 15 minute(s)
  - Rolling Window Size: 300 minute(s)
  - Forecast Horizon: 180 minute(s)
  - Prediction Time: 13.00
--------------------------------------------------
Preset 'b1':
  - Sampling Rate: 1 hour(s)
  - Rolling Window Size: 42 hour(s)
  - Forecast Horizon: 14 hour(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'b2':
  - Sampling Rate: 1 hour(s)
  - Rolling Window Size: 70 hour(s)
  - Forecast Horizon: 14 hour(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'c1':
  - Sampling Rate: 1 day(s)
  - Rolling Window Size: 15 day(s)
  - Forecast Horizon: 3 day(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'c2':
  - Sampling Rate: 1 day(s)
  - Rolling Window Size: 40 day(s)
  - Forecast Horizon: 5 day(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'd1':
  - Sampling Rate: 1 week(s)
  - Rolling Window Size: 16 week(s)
  - Forecast Horizon: 2 week(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'd2':
  - Sampling Rate: 1 week(s)
  - Rolling Window Size: 24 week(s)
  - Forecast Horizon: 3 week(s)
  - Prediction Time: 16.00
--------------------------------------------------
Preset 'd3':
  - Sampling Rate: 1 week(s)
  - Rolling Window Size: 48 week(s)
  - Forecast Horizon: 6 week(s)
  - Prediction Time: 16.00
--------------------------------------------------

In [7]:
#pred_manager.fine_tune_predictors(architectures_to_finetune=['LSTM'], types_to_finetune=["c1", "c2", "d1", "d2", "d3"], finetune_working_directory=WORKING_DIR_PREDICTORS, )  # if doing so, reinitialise pred_manager without "not_older_than_n_days"

## Portfolio

In [8]:
if scenario == "deployment":
    portfolio = KOCertificateSet.load_from_csv(
        file_path=filemgmt.most_recent_file(SAVED_PORTFOLIOS, ".csv", ["Scraped"]),
        underlying_price_series=data_manager.non_etf_env_interp_prices, )

    # update product details:
    for product in portfolio.ko_certificates:
        #product.update_product_details_from_scrape()  # often causes errors because it re-computes linear base price inference
        pass
    #portfolio.save_to_csv(SAVED_PORTFOLIOS / filemgmt.file_title("Saved Certificate Set", ".csv"))

elif scenario == "backtest":
    portfolio = KOCertificateSet.load_from_csv(
        file_path=filemgmt.most_recent_file(SAVED_PORTFOLIOS, ".csv", ["Artificial"]),
        underlying_price_series=data_manager.non_etf_env_interp_prices, )

In [9]:
#portfolio.plot_leverages()

{product.isin: product.base_price_change_per_annum for product in portfolio.ko_certificates}

{'DE000TT2CH77': 0.0858322168307789,
 'DE000HS3U0K3': 0.10249413716840139,
 'DE000TT0ZP72': 0.10267377918449805,
 'DE000TT1K2J8': -0.007407373058575084,
 'DE000TT1WHV8': 0.0911921965316913,
 'DE000HG75555': 0.08916083438139744,
 'DE000HS2W424': 0.029126213592232886,
 'DE000HS3GYD5': 0.10484784737686936,
 'DE000HS8DSJ0': 0.02999999999999836,
 'DE000FA0RD26': -0.10268376069452056,
 'DE000FA0Q232': -0.10604924804545268,
 'DE000SX0LHS4': 0.10335361233714935,
 'DE000HT52AV7': -0.030000000000001137}

## Backtest Schedule
https://github.com/tmorgan4/btgym_Kismuz/blob/master/btgym/strategy/base.py

In [10]:
if scenario == "backtest":
    result_frame = env_parametrisation_loop(
        env_price_series=data_manager.env_interp_prices,
        env_price_sampling_rate_minutes=data_manager.env_sampling_rate_minutes,
        env_product_set=portfolio,
        backtest_database_dir=SAVED_BACKTESTS,
        # varying params:
        predictor_instances=[
            #pred_manager.get_predictors_by_type_sorted(architecture='LSTM', preset_type='c2', return_instances=True, k_best=1),
            #pred_manager.get_predictors_by_type_sorted(architecture='LSTM', return_instances=True, k_best=2),
            pred_manager.get_predictors_by_type_sorted(architecture='LSTM',
                                                       return_instances=True, k_best=3),
            #pred_manager.get_predictors_by_type_sorted(architecture='LSTM',return_instances=True, k_best=4),
        ],
    
        # constant params:
        # 90 day expected return, sell -> buy -> highest leverage
        abs_potential_threshold_steps=[(.0025, .04, .1),
                                       ],
        # balanced, offensive, defensive
        trading_quantity_per_leverage_factor=[1, 1.25, 1.5, 1.75, 2,
                                              2.25, 2.5, 2.75, 3],
        sell_opposite_direction_if_no_cash=True,
        sell_all_opposite_products_if_no_cash=True,  #[False, True],
        include_open_leverage_category=False,
        precalculate_predictor_observations=True,
        leverage_categories=(1.0, 2.0, 3.0, 4.0, 5.0))
    result_frame

In [11]:
previous_frame = pd.read_csv(filemgmt.most_recent_file(SAVED_BACKTESTS))
previous_frame.sort_values(by='Mean', ascending=False)

,predictor_instances,abs_potential_threshold_steps,Mean,Median,StdDev,Min,Max,SharpeRatio,trading_quantity_per_leverage_factor,sell_opposite_direction_if_no_cash,sell_all_opposite_products_if_no_cash,include_open_leverage_category,precalculate_predictor_observations,leverage_categories,date
53,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.0025, 0.04, 0.1)",0.117417,0.074664,0.257760,-0.362711,1.962385,0.519197,2.50,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-25
54,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.0025, 0.04, 0.1)",0.116449,0.061945,0.259297,-0.362503,1.936245,0.517403,2.25,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-25
55,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.0025, 0.04, 0.1)",0.116275,0.064159,0.254523,-0.362294,1.923900,0.526368,2.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-25
41,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.0025, 0.04, 0.1)",0.116275,0.064159,0.254523,-0.362294,1.923900,0.526368,2.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-25
42,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.0025, 0.04, 0.1)",0.116031,0.070729,0.259417,-0.362310,2.011028,0.508570,3.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925]","(0.025, 0.075, 0.6)",0.006644,0.003478,0.100070,-0.291681,0.340071,0.225091,1.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
16,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925]","(0.035, 0.125, 0.7)",0.004820,0.001483,0.101482,-0.304426,0.339057,0.188869,1.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
17,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.035, 0.125, 0.7)",0.004645,-0.000053,0.101228,-0.224698,0.401642,0.179952,1.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
18,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.025, 0.075, 0.6)",0.004577,0.000697,0.099339,-0.230125,0.349942,0.190271,1.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24
19,"[LSTM_d3_ValHR0.9109, LSTM_d2_ValHR0.7925, LST...","(0.035, 0.125, 0.7)",0.003840,-0.000115,0.102606,-0.226911,0.387994,0.167632,1.00,True,True,False,True,"(1.0, 2.0, 3.0, 4.0, 5.0)",2025-08-24

## Environment

In [12]:
env = RLTradingEnv(price_series=data_manager.env_interp_prices,
                   price_sampling_rate_minutes=data_manager.env_sampling_rate_minutes,
                   predictor_instances=pred_manager.get_predictors_by_type_sorted(architecture='LSTM',
                                                                                  return_instances=True, k_best=3),
                   product_set=portfolio,
                   trading_quantity_per_leverage_factor=2.5,
                   sell_opposite_direction_if_no_cash=True, sell_all_opposite_products_if_no_cash=True,
                   include_open_leverage_category=False,
                   precalculate_predictor_observations=(scenario == 'backtest'),  # FALSE MAKES SENSE ONLY FOR REDUCED N_STEPS IN BACKTEST
                   leverage_categories=(1.0, 2.0, 3.0, 4.0, 5.0))  #, 5.5, 6.0, 6.5, 7.0))

Starting at 2015-9-24 although data is provided since 2014-10-23 to have sufficient information for all predictors.

In [13]:
#obs, _, _, _, info = env.step(3, track_portfolio_exposure=False)
#print(obs)
#print(info)
#self.open_positions"""

## Agent

### Manual Agent

In [14]:
agent = MultiProductAgent(observation_types=env.observation_types,
                          observation_horizons_minute=env.observation_horizons_minutes,
                          n_leverage_categories=len(env.leverage_categories),
                          abs_potential_threshold_steps=(.0025, .04, .1),  # (.04, .15, .7)
                          include_open_leverage_category=env.include_open_leverage_category,
                          potential_treshold_horizon_days=env.potential_horizon_days,
                          )

### RL Agent
With stable-baseline3 and pytorch.

Stable-Baselines3 is a reinforcement learning library built on top of PyTorch. It provides a set of pre-implemented RL algorithms and simplifies the process of training and evaluating RL models. It also includes a variety of useful tools for monitoring training progress and visualizing model behavior.

For training we will use Deep Q-Network (DQN). DQN is a reinforcement learning algorithm that uses a deep neural network to approximate the Q-value function. The Q-value function is a function that receives a status-action pair and outputs a value representing the expected cumulative reward for taking that action from that status, and continues playing following the optimal policy.

#### Agent Training

In [15]:
from stable_baselines3.common.env_checker import check_env
# check_env(env)

In [16]:
# MlpPolicy is policy used for training
# DummyVecEnc optimizes training through multiple independent variables
#env.verbose = False  # mute environment
#rl_agent = DQN('MlpPolicy', DummyVecEnv([lambda: env]), learning_rate=0.001, verbose=1)

In [17]:
#rl_agent.learn(total_timesteps=50000, log_interval=100, progress_bar=True)  # ~1s per iteration -> ~3600 iterations/h
#rl_agent.save(filemgmt.file_title('DQN Trading Agent 100k iterations', dtype_suffix='.pt'))

In [18]:
# only decision 'sell long 2.0-3.0' in backtest... what can cause stagnant decision-making?

In [19]:
# ponder:
# - training visualisation
# - reward shaping
# - initialisation
# - architecture

## Single Backtest

In [20]:
"""monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=rl_agent, track_portfolio_exposure_every=20,
                                                         reset_environment=True,
                                                         save_log_directory=TRAINING_LOGS, performance_time_unit='p.m.')"""

"monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=rl_agent, track_portfolio_exposure_every=20,\n                                                         reset_environment=True,\n                                                         save_log_directory=TRAINING_LOGS, performance_time_unit='p.m.')"

In [21]:
if scenario == 'backtest':
    monthly_policy, monthly_benchmark, statistics = env.run_env_backtest(agent=agent, track_portfolio_exposure_every=20,
                                                                         reset_environment=True,
                                                                         save_log_directory=TRAINING_LOGS,
                                                                         performance_time_unit='p.m.')

## Deployment

### Scrape Real-Time Data

#### DAX Price

In [32]:
if scenario == "deployment":
    # update interpolated data with scraping:
    data_manager.update(force_include_scraped=True)
    
    env.price_series = data_manager.env_interp_prices
    portfolio.update_all_price_series(data_manager.non_etf_env_interp_prices)
    
    # here one more step can be executed:
    env.current_step = env.total_steps - 2
    env.current_step_timestamp

Downloaded data ranged from	2014-10-23 15:31:00 to 2025-08-27 17:35:00
Will query the AlphaVantage API 1 times based on the specified time range. Queries:
 ['2025-08']

100%|██████████| 1/1 [00:01<00:00,  1.37s/it]

now ranges from				2014-10-23 15:31:00 to 2025-08-28 18:18:00

Interpolated data ranged from	2014-10-23 16:00:00 to 2025-08-28 16:00:00
Successfully downloaded price data from comdirect.
now ranges from					2014-10-23 16:00:00 to 2025-08-29 16:30:00

#### Wikifolio Data

In [35]:
# login to wikifolio:
driver = webinteraction.login_to_wikifolio(WIKIFOLIO_USER_KEY[0], WIKIFOLIO_USER_KEY[1])

In [36]:
# fetch relevant portfolio data:
wf_cash, wf_value, wf_shares_p_isin, wf_price_p_isin = webinteraction.scrape_portfolio_holdings_from_wikifolio(driver)

In [37]:
# update env cash:
env.cash = wf_cash

# update shares per product:
for isin, shares in wf_shares_p_isin.items():
    env.shares_per_product[isin] = shares

In [38]:
# derive price deviations:
closest_to_current_prices = env.product_set.price_frame.loc[:pd.Timestamp.now()].iloc[-1]
print(f"-------------------- Simulated product price deviations --------------------")
for isin, price in wf_price_p_isin.items():
    if isin in closest_to_current_prices.index:
        deviation = (closest_to_current_prices[isin] / price - 1) * 100
        print(f"{isin}:  {deviation:.2f}%\t\t(Env. price: {price:.2f},  \tWF price: {closest_to_current_prices[isin]:.2f})")

-------------------- Simulated product price deviations --------------------
DE000SX0LHS4:  -2.07%		(Env. price: 71.29,  	WF price: 69.82)
DE000FA0RD26:  -2.32%		(Env. price: 98.29,  	WF price: 96.01)
DE000HG75555:  1.79%		(Env. price: 94.43,  	WF price: 96.12)
DE000HS3GYD5:  2.85%		(Env. price: 6.59,  	WF price: 6.78)
DE000HS8DSJ0:  5.69%		(Env. price: 5.61,  	WF price: 5.93)
DE000TT0ZP72:  1.18%		(Env. price: 147.92,  	WF price: 149.67)
DE000TT1K2J8:  2.01%		(Env. price: 157.67,  	WF price: 160.83)
DE000TT1WHV8:  1.44%		(Env. price: 118.26,  	WF price: 119.97)
DE000TT2CH77:  1.60%		(Env. price: 106.86,  	WF price: 108.56)
DE000FA0Q232:  -2.71%		(Env. price: 83.19,  	WF price: 80.94)
DE000HS2W424:  3.53%		(Env. price: 7.53,  	WF price: 7.80)
DE000HS3U0K3:  2.70%		(Env. price: 6.07,  	WF price: 6.23)
DE000HT52AV7:  -3.42%		(Env. price: 56.13,  	WF price: 54.21)

In [39]:
add_missing = False

# see whether all product_set isins are included in wikifolio:
missing_isins = []
for product in env.product_set.ko_certificates:
    if product.isin not in wf_shares_p_isin.keys():
        print(f"Product {product.isin} not found in WF portfolio. {'Will be added.' if add_missing else 'Consider adding.'}")
        missing_isins.append(product.isin)
    
if add_missing: webinteraction.add_products_to_wikifolio(driver, missing_isins)

### Chatbot

In [40]:
chatter = WhatsAppChatbot("../private/chatbot.env", verbose=True)

In [ ]:
chatter("Hey! I just fetched wikifolio's statistics and today's price data. Now inferring today's predictions.")
chatter(f"Currently the environment is at {env.current_step_timestamp}.")

### Inference

In [42]:
env.open_positions

               Shares  Leverage     Price Direction  % Portfolio
DE000HS8DSJ0  82760.0  4.039224  6.024614      long    48.759152

In [43]:
from typing import Literal
from datetime import datetime

class TradeImplementor:
    def __init__(self):
        self.action_log = {}

    def __call__(self, isin: str, amount: int, action: Literal['buy', 'sell']):
        today = datetime.today().strftime('%Y-%m-%d %H_%M_%S')
        self.action_log[today] = {"isin": isin, "amount": amount, "action": action, "completed": False}
    
    # todo: implement action execution and set "completed" to True

In [44]:
env.open_positions

               Shares  Leverage     Price Direction  % Portfolio
DE000HS8DSJ0  82760.0  4.039224  6.024614      long    48.759152

In [45]:
action, _ = agent.predict(env.current_observation)
trade_implementor = TradeImplementor()
new_obs, _, done, truncated, info = env.step(action, track_portfolio_exposure=False, start_new_episode_if_finished=False,
                                             trade_implementation_callback=trade_implementor)
print(info)

[STEP 2831] Bought 85488.0 shares of DE000HS8DSJ0 (long with leverage in (4.0, 5.0)) at 5.934060937016019.
    Cash: 16683.121616374585, Holding: 997396.4880430283
{'Step': 2831, 'Time': '2025-08-29 16:00:00', 'Reward': -8491.54, 'Action': 'Buy long 4.0x - 5.0x', 'Avg. Expected Potential / 90d': 0.2264866800299109, 'Cash': 16683.12, 'Total': 1014079.61}

In [46]:
predictions_str_list = [f"{round(potential*100, 2)} % in {round(horizon_minutes / 60 / 14)} days" for potential, horizon_minutes in zip(env.current_potential_estimates, env.observation_horizons_minutes)]
prediction_str = "\n".join(predictions_str_list)  # will be included in next str:

In [51]:
explanatory_string = f"Based on the predictions\n\n{prediction_str}\n\n-> an average predicted potential of {env.current_avg_scaled_predicted_potential*100:.2f} % in {env.potential_horizon_days} days, the agent wants to {info['Action']}!"
explanatory_string

'Based on the predictions\n\n2.37 % in 5 days\n-0.01 % in 30 days\n-0.5 % in 15 days\n\n-> an average predicted potential of 22.65 % in 90 days, the agent wants to Buy long 4.0x - 5.0x!'

In [ ]:
chatter(explanatory_string)

### Execution

In [ ]:
chatter(f"Currently we have {wf_cash} EUR cash in the wikifolio ({wf_cash / wf_value * 100:.2f}%).")

In [ ]:
trade_str_list = []
for trade_dict in trade_implementor.action_log.values():
    if trade_dict["completed"]: continue  # only uncompleted trade
    
    trade_str_list.append(f"{trade_dict['action']} {trade_dict['amount'].item() if isinstance(trade_dict['amount'], np.float16) else trade_dict['amount']} shares of {trade_dict['isin']}.")

chatter("The resulting recommended trades are:")
for trade_str in trade_str_list:
    chatter(trade_str)

In [ ]:
chatter(f"Now the environment is at {env.current_step_timestamp}.")