# Price Data Download Notebook

In [1]:
import os
from calendar import day_abbr
from datetime import datetime

import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.select import Select
from selenium.common.exceptions import ElementClickInterceptedException
import yfinance as yf
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Literal
from tqdm import tqdm
from alpha_vantage.timeseries import TimeSeries
import matplotlib.pyplot as plt
from scipy.interpolate import interp1d

import src.utils.file_management as filemgmt
import src.utils.str_conversion as strconv
import src.pipeline.preprocessing as preprocessing
import src.pipeline.web_interaction as webinteraction

In [2]:
ROOT = Path().resolve().parent
DATA = ROOT / "data"
DAILY_PRICES = DATA / "daily_price_downloads"
SCRAPED_RAW_DOWNLOADS = DATA / "scraped_raw_downloads_archive"
MINUTELY_PRICES = DATA / "minutely_price_downloads"
INTERPOLATED_PRICES = DATA / "interpolated_prices_dax"
INTERPOLATED_SMOOTHED_PRICES = DATA / "interpolated_smoothed_prices_dax"
SAVED_MODELS = DATA / "saved_models"

PRIVATE_FILES = ROOT / "private"
AV_API_KEY_FILE = PRIVATE_FILES / "Alpha Vantage API Key.txt"
with open(AV_API_KEY_FILE) as file: AV_API_KEY = file.read()

WIKIFOLIO_KEY_FILE = PRIVATE_FILES / "Wikifolio key.txt"
with open(WIKIFOLIO_KEY_FILE) as file: WIKIFOLIO_USER_KEY = file.read().split('\n')

## Comdirect Scrape

In [3]:
def safe_click_element(driver: webdriver.Chrome, element):
    """
    Attempts to safely click on a web element by scrolling it into view and retrying up to three times
    before raising an exception. This is useful for handling cases where elements are not immediately
    clickable due to overlays or timing issues.

    Parameters
    ----------
    driver : webdriver.Chrome
        The instance of the Chrome WebDriver interacting with the web page.
    element
        The web element to be clicked.

    Raises
    ------
    ElementClickInterceptedException
        Raised if the element cannot be clicked successfully after three attempts.
    """
    driver.execute_script("arguments[0].scrollIntoView(true);", element)

    # 3 attempts to click:
    for attempt in range(3):
        try:
            element.click()
            return
        except ElementClickInterceptedException:
            time.sleep(2)

    # otherwise raise error:
    raise ElementClickInterceptedException("Failed to click element.")

def wait_for_then_locate_element(driver: webdriver.Chrome, xpath: str = None, id: str = None, timeout: int = 20):
    """
    Waits for an element to become present in the DOM and then locates it using either its
    XPath or ID. This function employs WebDriverWait to ensure the desired web element
    is available before attempting to locate it. If neither `xpath` nor `id` is provided, it
    raises a ValueError.

    Parameters
    ----------
    driver : webdriver.Chrome
        The Selenium WebDriver instance used to interact with the browser.
    xpath : str, optional
        The XPath of the web element to locate. Defaults to None.
    id : str, optional
        The ID of the web element to locate. Defaults to None.
    timeout : int, optional
        The maximum time to wait (in seconds) for the element to appear in the DOM.
        Defaults to 20 seconds.

    Returns
    -------
    WebElement
        The located web element using the provided XPath or ID.

    Raises
    ------
    ValueError
        If neither `xpath` nor `id` is provided.
    """
    if xpath is not None:
        WebDriverWait(driver, timeout).until(
            EC.presence_of_element_located((By.XPATH, xpath))
        )
        return driver.find_element(By.XPATH, xpath)
    elif id is not None:
        WebDriverWait(driver, timeout).until(
            EC.presence_of_element_located((By.ID, id))
        )
        return driver.find_element(By.ID, id)
    else:
        raise ValueError("Either xpath or id must be provided!")

In [22]:
raw_download_dir: Path = SCRAPED_RAW_DOWNLOADS
url: str = "https://www.comdirect.de/inf/fonds/detail/chart.html?ID_NOTATION=115802659&"
driver_executable_path: str = ""
verbose: bool = True

"""
Fetches daily price data from Comdirect and returns it as a pandas Series.

This function uses Selenium WebDriver to navigate the Comdirect website, accept cookies,
and download historical price data in CSV format. The downloaded data is then processed
and returned as a pandas Series with datetime index.

Parameters
----------
raw_download_dir : Path
    Directory where the downloaded CSV file will be stored.
url : str, optional
    URL of the Comdirect page to fetch the data from. Default is a specific fund page for DAX ETF.
    Beware, functioning with different URLs hasn't been tested yet.
driver_executable_path : str, optional
    Path to the Selenium WebDriver executable for Chrome.
verbose : bool, optional
    If True, prints a message upon successful completion.

Returns
-------
pd.Series
    A pandas Series with datetime index representing the price data sorted in ascending order.

Raises
------
TimeoutException
    If any of the web elements fail to load within the specified wait time using Selenium.
FileNotFoundError
    If the downloaded CSV file is not found in the specified directory.
ValueError
    If the downloaded CSV file does not contain valid data for processing.
"""
# download directory
chrome_options = webdriver.ChromeOptions()
prefs = {"download.default_directory": str(raw_download_dir),
         "download.prompt_for_download": False,
         "download.directory_upgrade": True,
         "safebrowsing.enabled": True}
chrome_options.add_experimental_option("prefs", prefs)

service = Service(executable_path=driver_executable_path)
driver = webdriver.Chrome(service=service, options=chrome_options)  # opens window, do not close!
driver.get(url)

# Set zoom to 50% (zoom out) to prevent display size issues
driver.execute_script("document.body.style.zoom='50%'")

# wait until page is loaded (based on presence of cookie pop-up):
pop_up = wait_for_then_locate_element(driver, "/html/body/com-consent-layer")
pop_up = pop_up.shadow_root  # access shadow subtree
cookie_button = pop_up.find_element(By.CSS_SELECTOR,
                                    "dialog div div com-button-area com-button")  # > div:nth-child(2) > div:nth-child(2) > com-button-area > com-button:nth-child(1)")
safe_click_element(driver, cookie_button)

# open quote list button:
quote_button = wait_for_then_locate_element(driver, id="openQuoteListButton")
safe_click_element(driver, quote_button)

# amend time resolution of quotes:
interval_dropdown_element = wait_for_then_locate_element(driver, xpath="""//*[@id="FORM_KURSDATEN"]/div[2]/div/div[2]/div[2]/div/div/select""")
interval_dropdown = Select(interval_dropdown_element)
interval_dropdown.select_by_visible_text("15 Minuten")

update_button = wait_for_then_locate_element(driver, """//*[@id="FORM_KURSDATEN"]/div[3]/div/button""")
safe_click_element(driver, update_button)
time.sleep(2)
# wait until download pop-up is loaded (based on presence of "button" table):
download_button = wait_for_then_locate_element(driver, xpath="""//*[@id="id_pricedata-layer_trigger-aria-description-wrapper"]/div[2]/div/div/div/div/div/div/div[2]/div/a""")
safe_click_element(driver, download_button)
time.sleep(10)  # wait for download to be finished
if verbose: print("Successfully downloaded price data from comdirect.")

# fetch download:
downloaded_frame = pd.read_csv(filemgmt.most_recent_file(raw_download_dir, ".csv", search_by='meta-data'),
                               sep=";", encoding="latin-1")

# format frame:
formatted_frame = downloaded_frame.reset_index().iloc[1:, :]
# close price is level_5:
formatted_frame.rename(columns={'level_0': 'date', 'level_1': 'time', 'level_5': 'price'}, inplace=True)

# type conversion:
formatted_frame['datetime'] = pd.to_datetime(
    formatted_frame['date'].astype(str) + ' ' + formatted_frame['time'].astype(str), dayfirst=True)
try:
    formatted_frame['price'] = pd.to_numeric(formatted_frame['price'].str.replace(',', '.'), errors='coerce')
except KeyError:
    formatted_frame['price'] = pd.to_numeric(formatted_frame['level_3'].str.replace(',', '.'), errors='coerce')

# return sorted series:
price_series = formatted_frame.set_index('datetime')['price']
print(price_series.sort_index())

Successfully downloaded price data from comdirect.
datetime
2025-09-15 15:30:00    44.3600
2025-09-15 15:48:00    44.3600
2025-09-15 16:01:00    44.2907
2025-09-15 16:16:00    44.4400
2025-09-15 16:30:00    44.4400
2025-09-15 16:45:00    44.4200
2025-09-15 17:04:00    44.4250
2025-09-15 17:31:00    44.3844
2025-09-15 17:47:00    44.4650
2025-09-15 18:04:00    44.4600
2025-09-15 18:19:00    44.4396
2025-09-15 18:35:00    44.4400
2025-09-15 18:52:00    44.4700
2025-09-15 19:08:00    44.4200
2025-09-15 19:15:00    44.4100
Name: price, dtype: float64

MaxRetryError: HTTPConnectionPool(host='localhost', port=58754): Max retries exceeded with url: /session/10f35fcd3d745a60138ad48e0a0a41be/element/f.BBF600DD66961A9921095A8FD8B7C9FF.d.C7275100FEE827CC15FD0D57CEC7FCD3.e.627/name (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x127f1e650>: Failed to establish a new connection: [Errno 61] Connection refused'))

In [20]:
"/html/body/div[17]/div/div[2]/div/div/div/div/div/div/div[2]/div/a"

Successfully downloaded price data from comdirect.
datetime
2025-09-04 15:30:00    44.09
2025-09-04 15:45:00    44.18
2025-09-04 16:00:00    44.08
Name: price, dtype: float64

In [31]:
downloaded_frame

                                                Global X DAX Germany ETF - USD DIS(WKN: A2PBCC Börse: Nasdaq)
Datum      Zeit  Eröffnung Hoch  Tief   Schluss                                            Volumen
04.09.2025 16:00 44,18     44,18 43,99  44,065                                           16.938,00
           15:45 44,08     44,18 44,05  44,18                                             6.411,00
           15:30 44,09     44,10 44,045 44,09                                             6.353,00

In [33]:
# format frame:
formatted_frame = downloaded_frame.reset_index().iloc[1:, :]
# close price is level_5:
formatted_frame.rename(columns={'level_0': 'date', 'level_1': 'time', 'level_5': 'price'}, inplace=True)

# type conversion:
formatted_frame['datetime'] = pd.to_datetime(
    formatted_frame['date'].astype(str) + ' ' + formatted_frame['time'].astype(str), dayfirst=True)
formatted_frame['price'] = pd.to_numeric(formatted_frame['price'].str.replace(',', '.'), errors='coerce')

# return sorted series:
price_series = formatted_frame.set_index('datetime')['price']
print(price_series.sort_index())

datetime
2025-09-04 15:30:00    44.090
2025-09-04 15:45:00    44.180
2025-09-04 16:00:00    44.065
Name: price, dtype: float64

## Wikifolio Scrape Development

In [129]:
def wait_for_then_locate_element(driver: webdriver.Chrome, xpath: str, timeout: int = 20):
    """
    Waits for a web element to be present in the DOM, located by the given XPath, before returning the element.

    Parameters
    ----------
    driver : webdriver.Chrome
        The web driver instance controlling the browser session.
    xpath : str
        The XPath of the web element to locate.
    timeout : int, optional
        The maximum number of seconds to wait for the element to be located (default is 20).

    Returns
    -------
    WebElement
        The located web element once it becomes available in the DOM.

    Raises
    ------
    TimeoutException
        If the web element is not located within the specified timeout.
    """
    WebDriverWait(driver, timeout).until(
        EC.presence_of_element_located((By.XPATH, xpath))
    )
    return driver.find_element(By.XPATH, xpath)

In [130]:
def login_to_wikifolio(username: str, password: str, wikifolio_id: str = "wfprtresen", driver_executable_path="") -> webdriver.Chrome:
    """
    Logs into the specified Wikifolio account and navigates to the desired page.

    This function automates the process of logging into a Wikifolio account using a given set
    of credentials and navigates to a specific Wikifolio ID page using a Selenium-based web driver.
    The function also handles common popups like cookie notices and region confirmation dialogs.

    Parameters
    ----------
    username : str
        The username or email address used for logging into the Wikifolio account.
    password : str
        The password associated with the specified username.
    wikifolio_id : str, optional
        The ID of the target Wikifolio page to be accessed after login.
        Defaults to "wfprtresen".
    driver_executable_path : str, optional
        Path to the ChromeDriver executable. If not provided, Selenium will use the default
        configured executable.

    Returns
    -------
    webdriver.Chrome
        An instance of the active Chrome WebDriver session after a successful login.
    """
    url = f"https://www.wikifolio.com/de/de/meine-wikifolios/trade/{wikifolio_id.lower()}"
    
    service = Service(executable_path=driver_executable_path)
    driver = webdriver.Chrome(service=service)  # opens window, do not close!
    driver.get(url)
    
    # cookie button:
    wait_for_then_locate_element(driver, "/html/body/div[1]/div/div[4]/div[1]/div/div[2]/button[2]").click()
    
    # region button (appears after mouse movement)
    time.sleep(1)
    actions = webdriver.ActionChains(driver)
    actions.move_by_offset(10, 5).perform()  # moves mouse 10px right, 5px down from current position
    wait_for_then_locate_element(driver, "/html/body/div[7]/div[3]/div/section/footer/div/button").click()
    
    # login query button:
    wait_for_then_locate_element(driver, "/html/body/div[5]/div[3]/div/section/div/div[1]/button").click()
    
    # input login data:
    wait_for_then_locate_element(driver, "/html/body/div[5]/div[3]/div/section/div/form/div/div[1]/input").send_keys(username)
    wait_for_then_locate_element(driver, "/html/body/div[5]/div[3]/div/section/div/form/div/div[2]/input").send_keys(password)
    # submit:
    wait_for_then_locate_element(driver, "/html/body/div[5]/div[3]/div/section/div/form/div/button").click()
    
    return driver

In [131]:
def add_products_to_wikifolio(driver: webdriver.Chrome, isins_to_add: list[str]):
    """
    Adds a list of products identified by their ISINs to a wikifolio.

    Parameters
    ----------
    driver : webdriver.Chrome
        An instance of Chrome WebDriver. The driver must be logged in to wikifolio.
    isins_to_add : list[str]
        A list of ISINs to add to the wikifolio. If an ISIN is already included, no action will be taken for it.

    """
    ### add isins from provided list (if already included, doesn't matter)
    # driver has to be logged into wikifolio already
    if isins_to_add is not None:
        for isin in isins_to_add:
            add_isin_input = wait_for_then_locate_element(driver, "/html/body/div[3]/main/div[3]/div[2]/div[1]/div/div/div[1]/div[2]/div/div/div[2]/div[1]/div[1]/div/div[2]/div/span[1]/input[2]")
            add_isin_input.send_keys(isin)  # slow down to prevent errors
            add_product_button = wait_for_then_locate_element(driver, "/html/body/div[3]/main/div[3]/div[2]/div[1]/div/div/div[1]/div[2]/div/div/div[2]/div[1]/div[1]/div/div[2]/div/span[1]/div/div/div[2]")
            add_product_button.click()
            time.sleep(2)  # slow down to prevent errors

In [132]:
def scrape_portfolio_holdings_from_wikifolio(driver: webdriver.Chrome) -> tuple[float, float, dict[str, float]]:
    """
    Scrapes portfolio holdings from a logged-in Wikifolio account.

    This function extracts data about the cash balance, total portfolio value, and shares per ISIN from a specific table on the Wikifolio website. It requires the user to already be logged into their Wikifolio account before calling this function.

    Parameters
    ----------
    driver : webdriver.Chrome
        A Selenium WebDriver instance that must already be logged into Wikifolio and pointing to the relevant portfolio page.

    Returns
    -------
    tuple[float, float, dict[str, float]]
        A tuple containing:
        - `wf_cash` : The cash balance in the portfolio.
        - `wf_total` : The total value of the portfolio.
        - `shares_p_isin_dict` : A dictionary mapping ISINs (International Securities Identification Numbers) to the number of shares held for each.
    """
    # driver has to be logged into wikifolio (login_to_wikifolio method) already
    
    ### fetch shares per isin:
    shares_p_isin_dict = {}
    # locate relevant table:
    product_table = wait_for_then_locate_element(driver, "/html/body/div[3]/main/div[3]/div[2]/div[1]/div/div/div[1]/div[2]/div/div/div[1]/div/div/table/tbody")
    product_table_rows = product_table.find_elements(By.XPATH, "tr")
    for row_ind, row in enumerate(product_table_rows):
        # skip irrelevant rows
        if row_ind == 0: continue  # column label row
        elif row_ind == len(product_table_rows) - 2:  # cash 
            wf_cash_entry = row.find_element(By.XPATH, "td[4]/div")
            wf_cash = strconv.str_to_float(wf_cash_entry.text)
            continue
        elif row_ind == len(product_table_rows) - 1:  # portfolio value
            wf_total_entry = row.find_element(By.XPATH, "td[4]/div")
            wf_total = strconv.str_to_float(wf_total_entry.text)
            continue
        
        # fetch and convert relevant entries:
        isin_entry = row.find_element(By.XPATH, "td[1]/div/div/div")
        isin = isin_entry.text
        shares_count_entry = row.find_element(By.XPATH, "td[3]/div")
        shares_count = strconv.str_to_float(shares_count_entry.text)
        
        shares_p_isin_dict[isin] = shares_count
        
    return wf_cash, wf_total, shares_p_isin_dict

In [141]:
driver = login_to_wikifolio(WIKIFOLIO_USER_KEY[0], WIKIFOLIO_USER_KEY[1])

In [134]:
add_products_to_wikifolio(driver, isins_to_add=["DE000TT2CH77",
                                                "DE000HS3U0K3",
                                                "DE000TT0ZP72",
                                                "DE000TT1WHV8",
                                                "DE000HG75555",
                                                "DE000HS2W424",
                                                "DE000HS3GYD5",
                                                "DE000HS8DSJ0",
                                                "DE000FA0RD26",
                                                "DE000FA0Q232",
                                                "DE000SX0LHS4",
                                                "DE000SX0LHS4",
                                                "DE000HT52AV7",
                                                "DE000HT52AV7",
                                                ])

In [142]:
cash, value, shares_p_isin = scrape_portfolio_holdings_from_wikifolio(driver)

In [143]:
cash

999896.051

In [144]:
value

999896.051

In [145]:
shares_p_isin

{'DE000SX0LHS4': 0.0,
 'DE000FA0RD26': 0.0,
 'DE000HG75555': 0.0,
 'DE000HS3GYD5': 0.0,
 'DE000HS8DSJ0': 0.0,
 'DE000TT0ZP72': 0.0,
 'DE000TT1WHV8': 0.0,
 'DE000TT2CH77': 0.0,
 'DE000FA0Q232': 0.0,
 'DE000HS2W424': 0.0,
 'DE000HS3U0K3': 0.0,
 'DE000HT52AV7': 0.0}

In [21]:
submit_button = driver.find_element(By.XPATH, "/html/body/div[5]/div[3]/div/section/div/form/div/button")
submit_button.click()

In [7]:
# wait until page is loaded (based on presence of cookie pop-up):
WebDriverWait(driver, 5).until(
    EC.presence_of_element_located((By.XPATH, "/html/body/com-consent-layer"))
)

def wait_for_then_locate_element(driver: webdriver.Chrome, xpath: str, timeout: int = 5,
                                   ):
    WebDriverWait(driver, timeout).until(
        EC.presence_of_element_located((By.XPATH, xpath))
    )
    return driver.find_element(By.XPATH, xpath)

# accept cookie button (is hidden in shadow-subtree)
pop_up = driver.find_elements(By.XPATH, "/html/body/com-consent-layer")[0]
pop_up = pop_up.shadow_root  # access shadow subtree

date
2025-08-26 15:30:05    44.8275
2025-08-26 15:32:25    44.9700
2025-08-26 15:35:09    44.8850
2025-08-26 15:35:54    44.8166
2025-08-26 15:37:26    44.9590
                        ...
2025-08-26 20:06:51    44.7950
2025-08-26 20:09:58    44.8268
2025-08-26 20:22:29    44.8268
2025-08-26 20:32:37    44.8294
2025-08-26 20:33:48    44.8350
Name: close, Length: 92, dtype: float64

## Download from AlphaVantage
(Restricted to 25 daily free requests)

We are downloading DAX data from a USD dax-based ETF (https://de.finance.yahoo.com/quote/DAX/?guccounter=1), issued on 22nd October 2014. This is because AlphaVantage doesn't offer Index data.. Search better solution!

### Execution

In [7]:
ts = TimeSeries(key=AV_API_KEY)
search = ts.get_symbol_search("dax")[0]

In [14]:
search

,1. symbol,2. name,3. type,4. region,5. marketOpen,6. marketClose,7. timezone,8. currency,9. matchScore
0,DAX,GLOBAL X DAX GERMANY ETF,ETF,United States,09:30,16:00,UTC-04,USD,1.0000
1,DAXXF,iSharesCore DAX UCITS ETF (DE) EUR (Acc),ETF,United States,09:30,16:00,UTC-04,USD,0.7500
2,DAX.PAR,Multi Units Luxembourg - Lyxor DAX (DR) UCITS ETF,ETF,Paris,09:00,17:30,UTC+02,EUR,0.6667
3,DAX3.LON,Leverage Shares 3x Long Germany 40 ETP Securities,ETF,United Kingdom,08:00,16:30,UTC+01,USD,0.6667
4,DAXX.LON,MULTI-UNITS LUXEMBOURG - Lyxor DAX (DR) UCITS ...,ETF,United Kingdom,08:00,16:30,UTC+01,GBX,0.6667
5,DXR,Daxor Corp,Equity,United States,09:30,16:00,UTC-04,USD,0.6667
6,DX5.FRK,DAXOR CORP. DL -01,Equity,Frankfurt,08:00,20:00,UTC+02,EUR,0.5000

In [9]:
search.iloc[2, 0]

'DAX.PAR'

In [13]:
ts.get_intraday("DAX.DEX", outputsize="full")

ValueError: Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_INTRADAY.

In [4]:
frame = preprocessing.get_data_from_alphavantage(AV_API_KEY,
                                                 ticker='DAX',
                                                 # save_path=MINUTELY_PRICES,
                                                 start_year_month=(2025, 7),
                                                 end_year_month=(2025, 7),
                                                 price_csv_dir_to_concat=MINUTELY_PRICES,
                                                 time_increment='6h')
frame

Will query the AlphaVantage API 1 times based on the specified time range. Queries:
 ['2025-07']

100%|██████████| 1/1 [00:01<00:00,  1.38s/it]

                     1. open  2. high  3. low  4. close  5. volume
date
2025-07-01 04:02:00    44.93    44.93   44.93     44.93        1.0
2025-07-01 04:45:00    44.93    44.93   44.93     44.93        1.0
2025-07-01 07:02:00    44.93    44.93   44.93     44.93        3.0
2025-07-01 07:31:00    44.90    44.90   44.90     44.90      100.0
2025-07-01 08:00:00    44.93    45.31   44.93     44.93       12.0
...                      ...      ...     ...       ...        ...
2025-07-31 17:46:00    43.51    43.51   43.51     43.51      100.0
2025-07-31 18:32:00    43.51    43.51   43.51     43.51       12.0
2025-07-31 18:53:00    43.50    43.50   43.49     43.49      100.0
2025-07-31 19:04:00    43.49    43.49   43.49     43.49       10.0
2025-07-31 19:48:00    43.46    43.46   43.46     43.46       80.0

[3321 rows x 5 columns]

## Interpolation

In [3]:
# date import parameters:
date_column = 'date'
price_column = '4. close'
latest_file_path = filemgmt.most_recent_file(MINUTELY_PRICES, ".csv", "DAX")

In [8]:

# interpolation parameters:
sampling_rate_to_be_interpolated = '7d'
moving_average_size = None  #'21d'  # triple the sampling rate
manual_operating_hours = (8, 22)
custom_start_hour = 16
custom_start_minute = 0

interpolated_prices = preprocessing.time_interpolation_new_sampling_rate(datamanager.downloaded_prices,
                                                                         
                                                                         datetime_column=date_column,
                                                                         new_sampling_rate=sampling_rate_to_be_interpolated,
                                                                         moving_average_window_size=moving_average_size,
                                                                         custom_start_hour=custom_start_hour,
                                                                         custom_start_minute=custom_start_minute,
                                                                         verbose=True,
                                                                         manual_operating_hours=manual_operating_hours,
                                                                         save_path=INTERPOLATED_SMOOTHED_PRICES,
                                                                         save_title_identifier='DAX Close')

interpolated_prices

Excluded every entry on Saturday or Sunday.
Excluded every entry before hour 8 and after hour 22.
New sampling rate (7d) is higher than current lowest time unit (1min).
Therefore some existing indices will be removed to match the new sampling rate, while all information will be kept through the interpolation procedure.

                         close
date
2014-10-23 16:00:00  19.859246
2014-10-30 16:00:00  20.091760
2014-11-06 16:00:00  20.223222
2014-11-13 16:00:00  20.124641
2014-11-20 16:00:00  20.842549
...                        ...
2025-07-17 16:00:00  45.120000
2025-07-24 16:00:00  45.420000
2025-07-31 16:00:00  43.660000
2025-08-07 16:00:00  44.910000
2025-08-14 16:00:00  45.304800

[565 rows x 1 columns]

In [19]:
def print_time_index_entries_p_day(df: pd.DataFrame) -> None:
    df = df.copy()
    df['counter'] = 1
    statistics = df.counter.groupby(by=[df.index.year, df.index.day_of_year]).sum().describe()
    print('Average entries p. day:\t\t\t\t\t', statistics['mean'])
    print('Min. entries p. day:\t\t\t\t\t', statistics['min'])
    print('Lowest 25% entries p. day are below:\t', statistics['25%'])
    print('Lowest 50% entries p. day are below:\t', statistics['50%'])
    print('Lowest 75% entries p. day are below:\t', statistics['75%'])
    print('Max. entries p. day:\t\t\t\t\t', statistics['max'])


# interesting statistics to decide the sampling rate:    
print_time_index_entries_p_day(interpolated_prices)

Average entries p. day:					 55.985063752276865
Min. entries p. day:					 24.0
Lowest 25% entries p. day are below:	 56.0
Lowest 50% entries p. day are below:	 56.0
Lowest 75% entries p. day are below:	 56.0
Max. entries p. day:					 56.0

## ETF - Index Price Relation
Download last interpolated prices and compute relation between ETF and index. **Issue:** ETF notates in US-$, index in EUR...

In [3]:
dax_etf_prices = pd.read_csv(filemgmt.most_recent_file(INTERPOLATED_PRICES, ".csv", "15min"))
dax_etf_prices['date'] = pd.to_datetime(dax_etf_prices.date)
dax_etf_prices.set_index('date', inplace=True)
dax_etf_prices

                         close
date
2014-10-23 16:00:00  19.859246
2014-10-23 16:15:00  19.869064
2014-10-23 16:30:00  19.883171
2014-10-23 16:45:00  19.897279
2014-10-23 17:00:00  19.908301
...                        ...
2025-06-04 20:45:00  44.849950
2025-06-04 21:00:00  44.790000
2025-06-04 21:15:00  44.780000
2025-06-04 21:30:00  44.795000
2025-06-04 21:45:00  44.780000

[155088 rows x 1 columns]

In [4]:
dates = ['2025-06-04 18:00:00',     '2025-06-02 17:00:00',  '2025-06-03 12:00:00',  '2025-05-30 17:00:00']
prices = [24276.48,                 23942.52,               23962.40,               23997.71]

In [381]:
multipliers = [price / dax_etf_prices.loc[date, 'close'] for price, date in zip(prices, dates)]
relations = pd.Series(index=dates, data=multipliers, name='Index Multiplier').sort_index()
print(relations.mean())
relations

543.3079783216567

2025-05-30 17:00:00    545.401260
2025-06-02 17:00:00    541.012767
2025-06-03 12:00:00    544.569059
2025-06-04 18:00:00    542.248827
Name: Index Multiplier, dtype: float64

## DataDownloader Class

In [25]:
class StockPriceDataManager:
    """
        Class for managing stock price data, including downloading, interpolating, and adjusting ETF data.

        Attributes
        ----------
        ticker_symbol : str
            The ticker symbol for the stock or ETF.
        download_dir : Path
            Directory where downloaded data files are stored.
        interpolated_files_dir : Path
            Directory where interpolated data files are stored.
        env_sampling_rate_minutes : Literal[15, 60, 1440]
            Sampling rate in minutes for interpolated data.
        price_column : Literal['low', 'high', 'open', 'close']
            Price column to use for calculations and interpolations.
        is_etf_price_data : bool
            Indicates if the data pertains to ETF prices.
        non_etf_time_price_tuples : [(pd.Timestamp, float)]
            Time and price tuples for non-ETF counterpart data.
        download_time_increment : str
            Time increment for scheduling downloads, e.g., "6h".
        manual_operating_h_tuple : (int, int)
            Tuple representing manual operating hours (start, end).
        custom_start_h_min_tuple : (int, int)
            Tuple representing custom operating start time (hour, minute).

        Properties
        ----------
        non_etf_time_price_tuples : tuple
            Time and price tuples for non-ETF counterpart data.
        non_etf_price_factor : float
            Factor for converting ETF price data to non-ETF price data.
        env_sampling_rate_str : str
            String representation of the environment sampling rate.
        a_sampling_rate_str : str
            String representation of a-predictor sampling rate.
        b_sampling_rate_str : str
            String representation of b-predictor sampling rate.
        c_sampling_rate_str : str
            String representation of c-predictor sampling rate.
        d_sampling_rate_str : str
            String representation of d-predictor sampling rate.
        env_interp_prices : pd.Series
            Interpolated prices for the environment sampling rate.
        non_etf_env_interp_prices : pd.Series
            Interpolated prices for the environment sampling rate, multiplied by the non-ETF price factor.
        a_interp_prices : pd.Series
            Interpolated prices for the a-predictor sampling rate.
        b_interp_prices : pd.Series
            Interpolated prices for the b-predictor sampling rate.
        c_interp_prices : pd.Series
            Interpolated prices for the c-predictor sampling rate.
        d_interp_prices : pd.Series
            Interpolated prices for the d-predictor sampling rate.
        downloaded_price_frame : pd.DataFrame
            Dataframe of the most recently downloaded price data.
        downloaded_prices : pd.Series
            Series of the most recently downloaded prices according to the specified price column.
        interp_data_time_range : (pd.Timestamp, pd.Timestamp)
            Time range of the interpolated data.
        downloaded_data_time_range : (pd.Timestamp, pd.Timestamp)
            Time range of the downloaded data.

        Methods
        -------
        download_new_data()
            Downloads the most recent price data from AlphaVantage.
    """
    def __init__(self,
                 ticker_symbol: str,
                 download_dir: Path,
                 interpolated_files_dir: Path,
                 alpha_vantage_api_key: str,
                 env_sampling_rate_minutes: Literal[15, 60, 1440] = 15,
                 price_column: Literal['low', 'high', 'open', 'close'] = 'close',
                 is_etf_price_data: bool = False,
                 non_etf_time_price_tuples: [(pd.Timestamp, float)] = None,
                 download_time_increment: str = "6h",  # for US downloads
                 manual_operating_h_tuple: (int, int) = (8, 22),
                 custom_start_h_min_tuple: (int, int) = (16, 0),
                 ):
        self.ticker_symbol = ticker_symbol
        self.download_dir = download_dir
        self.interpolated_files_dir = interpolated_files_dir
        self._alpha_vantage_api_key = alpha_vantage_api_key
        self.env_sampling_rate_minutes = env_sampling_rate_minutes
        self.price_column = price_column
        self.is_etf_price_data = is_etf_price_data
        self._non_etf_time_price_tuples = non_etf_time_price_tuples
        self.download_time_increment = download_time_increment
        self.manual_operating_h_tuple = manual_operating_h_tuple
        self.custom_start_h_min_tuple = custom_start_h_min_tuple

        # placeholders for properties:
        self._non_etf_price_factor = None

        # not necesssary, reading out is enough:
        self._present_data_timerange = None

    #### Amenable Properties ####
    @property
    def non_etf_time_price_tuples(self) -> tuple:
        return self._non_etf_time_price_tuples
    @non_etf_time_price_tuples.setter
    def non_etf_time_price_tuples(self, value: tuple) -> None:
        self._non_etf_time_price_tuples = value
        self._non_etf_price_factor = None

    #### Saved Properties ####
    @property
    def non_etf_price_factor(self) -> float:
        """
        Fetches or calculates the non-ETF price factor for converting ETF price data into its underlying equivalent.

        Returns
        -------
        float
            A factor to adjust ETF price data, defaulting to 1.0 for non-ETF data. Raises an exception if the required data for computation is missing.

        Raises
        ------
        AttributeError
            If the non-ETF time-price tuples are not provided while ETF price data conversion is needed.
        """
        if not self.is_etf_price_data: return 1.0

        if self._non_etf_price_factor is None:
            if self._non_etf_time_price_tuples is None:
                raise AttributeError("Non-etf time-price tuples need to be provided for conversion of ETF data into underlying.")
            # compute multipliers and take mean:
            multipliers = [price / self.env_interp_prices.loc[date] for date, price in self.non_etf_time_price_tuples]
            self._non_etf_price_factor = np.mean(multipliers)
        return self._non_etf_price_factor

    ### Read-out at Runtime Properties ####
    ## sampling rates:
    @property
    def env_sampling_rate_str(self) -> str:
        """ Timedelta string related to environment sampling rate based on self.env_sampling_rate_minutes """
        minutes_to_str_dict = {15: self.a_sampling_rate_str, 60: self.b_sampling_rate_str, 1440: self.c_sampling_rate_str}
        return minutes_to_str_dict[self.env_sampling_rate_minutes]

    @property  # todo: read out global variable?
    def a_sampling_rate_str(self) -> str:
        return "15min"

    @property  # todo: read out global variable?
    def b_sampling_rate_str(self) -> str:
        return "60min"

    @property  # todo: read out global variable?
    def c_sampling_rate_str(self) -> str:
        return "1d"

    @property  # todo: read out global variable?
    def d_sampling_rate_str(self) -> str:
        return "7d"

    ## price frames:
    @property
    def env_interp_prices(self) -> pd.Series:
        """ Interpolated prices sampled at env_sampling_rate_minutes. """
        return preprocessing.read_price_csv(
            filemgmt.most_recent_file(self.interpolated_files_dir,
                                      suffix_to_consider=".csv",
                                      file_title_keywords=[self.ticker_symbol, self.env_sampling_rate_str]),
            date_column='date', price_column=self.price_column)

    @property
    def non_etf_env_interp_prices(self) -> pd.Series:
        """ Interpolated prices sampled at env_sampling_rate_minutes and multiplied by non_etf_price_factor. """
        return preprocessing.read_price_csv(
            filemgmt.most_recent_file(self.interpolated_files_dir,
                                      suffix_to_consider=".csv",
                                      file_title_keywords=[self.ticker_symbol, self.env_sampling_rate_str]),
            date_column='date', price_column=self.price_column) * self.non_etf_price_factor  # multiply with non-etf-factor

    @property
    def a_interp_prices(self) -> pd.Series:
        """ Interpolated prices sampled at a-predictor-type sampling rate. """
        return preprocessing.read_price_csv(
            filemgmt.most_recent_file(self.interpolated_files_dir,
                                      suffix_to_consider=".csv",
                                      file_title_keywords=[self.ticker_symbol, self.a_sampling_rate_str]),
            date_column='date', price_column=self.price_column)

    @property
    def b_interp_prices(self) -> pd.Series:
        """ Interpolated prices sampled at b-predictor-type sampling rate. """
        return preprocessing.read_price_csv(
            filemgmt.most_recent_file(self.interpolated_files_dir,
                                      suffix_to_consider=".csv",
                                      file_title_keywords=[self.ticker_symbol, self.env_sampling_rate_str]),
            date_column='date', price_column=self.price_column)

    @property
    def c_interp_prices(self) -> pd.Series:
        """ Interpolated prices sampled at c-predictor-type sampling rate. """
        return preprocessing.read_price_csv(
            filemgmt.most_recent_file(self.interpolated_files_dir,
                                      suffix_to_consider=".csv",
                                      file_title_keywords=[self.ticker_symbol, self.c_sampling_rate_str]),
            date_column='date', price_column=self.price_column)

    @property
    def d_interp_prices(self) -> pd.Series:
        """ Interpolated prices sampled at d-predictor-type sampling rate. """
        return preprocessing.read_price_csv(
            filemgmt.most_recent_file(self.interpolated_files_dir,
                                      suffix_to_consider=".csv",
                                      file_title_keywords=[self.ticker_symbol, self.d_sampling_rate_str]),
            date_column='date', price_column=self.price_column)

    @property
    def downloaded_price_frame(self) -> pd.DataFrame:
        """ Most recent price download dataframe. """
        frame = pd.read_csv(
            filemgmt.most_recent_file(self.download_dir,
                                      suffix_to_consider=".csv",
                                      file_title_keywords=[self.ticker_symbol])
        )
        frame['date'] = pd.to_datetime(frame['date'])
        return frame.set_index('date').dropna(axis=0)

    @property
    def downloaded_prices(self) -> pd.Series:
        """ Most recent price download series according to self.price_column. """
        alpha_vantage_column_renaming = {'1. open': 'open', '2. high': 'high', '3. low': 'low', '4. close': 'close'}
        price_frame = self.downloaded_price_frame.rename(columns=alpha_vantage_column_renaming)
        return price_frame[self.price_column]

    ## other:
    @property
    def interp_data_time_range(self) -> (pd.Timestamp, pd.Timestamp):
        """ Time range of interpolated data. """
        date_times = self.env_interp_prices.index  # we assume all time ranges are equal because all are updated jointly
        return date_times.min(), date_times.max()

    @property
    def downloaded_data_time_range(self) -> (pd.Timestamp, pd.Timestamp):
        """ Time range of downloaded data. """
        date_times = self.downloaded_prices.index  # we assume all time ranges are equal because all are updated jointly
        return date_times.min(), date_times.max()

    #### Methods ####
    def download_new_data(self):
        """ Download most recent data from AlphaVantage """
        # define timerange to download:
        latest_data = self.downloaded_data_time_range[1]
        start_tuple = (latest_data.year, latest_data.month)
        end_tuple = (datetime.today().year, datetime.today().month)

        preprocessing.get_data_from_alphavantage(self._alpha_vantage_api_key,
                                                 ticker=self.ticker_symbol,
                                                 save_path=self.download_dir,
                                                 start_year_month=start_tuple,
                                                 end_year_month=end_tuple,
                                                 price_frame_to_concat=self.downloaded_price_frame,
                                                 time_increment=self.download_time_increment)

    def update_interpolated_data(self):
        """ Interpolate and sample all price files based on most recent data download. """
        for sampling_rate_str in [self.a_sampling_rate_str, self.b_sampling_rate_str, self.c_sampling_rate_str,
                                  self.d_sampling_rate_str]:
            preprocessing.time_interpolation_new_sampling_rate(price_series=self.downloaded_prices,
                                                                   datetime_column='date',
                                                                   new_sampling_rate=sampling_rate_str,
                                                                   moving_average_window_size=None,
                                                                   custom_start_hour=
                                                                   self.custom_start_h_min_tuple[0],
                                                                   custom_start_minute=
                                                                   self.custom_start_h_min_tuple[1],
                                                                   verbose=False,
                                                                   manual_operating_hours=self.manual_operating_h_tuple,
                                                                   save_path=self.interpolated_files_dir,
                                                                   save_title_identifier=f'{self.ticker_symbol} {self.price_column}')
            
    def update(self):
        """ Update downloaded and interpolated data. """
        print(f"Downloaded data ranged from\t{self.downloaded_data_time_range[0]} to {self.downloaded_data_time_range[1]}")
        self.download_new_data()
        print(f"now ranges from\t\t\t\t{self.downloaded_data_time_range[0]} to {self.downloaded_data_time_range[1]}")
        print(f"\nInterpolated data ranged from\t{self.interp_data_time_range[0]} to {self.interp_data_time_range[1]}")
        self.update_interpolated_data()
        print(f"now ranges from\t\t\t\t\t{self.interp_data_time_range[0]} to {self.interp_data_time_range[1]}")

In [26]:
datamanager = StockPriceDataManager(ticker_symbol='DAX',
                                    download_dir=MINUTELY_PRICES,
                                    interpolated_files_dir=INTERPOLATED_PRICES,
                                    alpha_vantage_api_key=AV_API_KEY,
                                    env_sampling_rate_minutes=15,
                                    is_etf_price_data=True,
                                    non_etf_time_price_tuples=[('2025-06-04 18:00:00', 24276.48),
                                                               ('2025-06-02 17:00:00', 23942.52),
                                                               ('2025-06-03 12:00:00', 23962.40),
                                                               ('2025-05-30 17:00:00', 23997.71)]
                                    )

In [27]:
datamanager.update()

Downloaded data ranged from	2014-10-23 15:31:00 to 2025-08-20 17:53:00
Will query the AlphaVantage API 1 times based on the specified time range. Queries:
 ['2025-08']

100%|██████████| 1/1 [00:00<00:00,  1.84it/s]

now ranges from				2014-10-23 15:31:00 to 2025-08-20 17:53:00

Interpolated data ranged from	2014-10-23 16:00:00 to 2025-08-20 17:45:00
now ranges from				2014-10-23 16:00:00 to 2025-08-20 17:45:00